### ISSUE TITLE
Are past events interesting?

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#102]
Do we need to show past events in the event list? The work I just spent 40 mins on would be wasted if they aren't, but I don't really see the use case.

Whaddaya think?

**Comment by pferdefleisch** [comment]
If they are, I would like an API filter ;)

**Comment by klappradla** [comment]
I do not show them in the web app, but the commit adding this is not pushed yet (still need to add some more stuff to it).

**Comment by klappradla** [comment]
712507f4fe96a99021b57d043e650274d1d2dccf adds pagination to the list + only show upcoming events. I will next also filter to **not** show `pending` events.

**Comment by klappradla** [comment]
Ok, so no past events (`show` will still work for past though for convenience). API is updated to only give you upcoming ones on index.

closing this then.
