### ISSUE TITLE
Mobile Apps Profile Screen

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#103]
What should be part of the Profile Screen on the mobile apps?

Following items are possible:

- [ ] Edit Profile Infos (Email, Name, Password, ...) -> API needed

- [ ] Abilities Picker (Fähigkeiten) -> API needed

- [ ] Languages Picker (Sprachen) -> API needed

- [ ] Option to delete profile

- [x] Option to log out

- [x] Link to App Store - Rating / Feedback

- [x] Share the App (Link to App Store)

- [x] Terms & Conditions 

- [x] Open Source Licenses

**Comment by haslinger** [comment]
2 quick wins: Api Endpoints for languages and abilities.

I think it's easiest to return two arrays of language ids and ability ids on profile update.

User endpoints should probably return assigned data for languages and abilities as well.

I'll continue here tomorrow, April 14th.

**Comment by haslinger** [comment]
@markusrubey api events#index are now restricted to published elements (which is now a new attribute)

**Comment by haslinger** [comment]
The api now has a new endpoint to update a user's data. Please have a look in the API docs for details and [an example](https://github.com/where2help/where2help/wiki/API-Example:-Update-user-profile) on how to use the new endpoint update_profile.

**Comment by markusrubey** [comment]
Thanks @haslinger, will check it out asap!

**Comment by haslinger** [comment]
@markusrubey : Did you find time to look into the new api end points. Is there anything missing right now?

**Comment by markusrubey** [comment]
@haslinger Sorry, not yet. Probably have more time in a week. But if the functionality of the web app profile is covered, as it seems to be the case, I'm not missing anything.
