### ISSUE TITLE
Service and job to fetch address coordinates

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#104]
We need a service enqueued as a background job to fetch the coordinates for an event's address-string.

We can use Vienna's ["Adresservice"](https://www.data.gv.at/katalog/dataset/c223b93a-2634-4f06-ac73-8709b9e16888) API for this.

**Comment by ramonh** [comment]
As discussed, we'll instead use autocompletion on the address field to remotely fetch the latitude and longitude of an address.

**Comment by ramonh** [comment]
Resolved as of 57ea662

**Comment by haslinger** [comment]
I know tested with all addresses I ever lived in Vienna and it worked perfectly. The icon on the map is always exactly the right spot. That's awesome.

Two things to consider:
- The map itself is quite restricted in height. Wouldn't it be better with let's say, twice the height?
- You can enter incomplete addresses by not selecting the dropdown. (I did so unintentionally by pressing ENTER before TAB)

**Comment by ramonh** [comment]
Thanks @haslinger, I appreciate your help!

I agree that the map could be taller. Dunno if twice as much might be too high, but let's see.

I set up the field so that even if you don't select a suggestion, it'll slurp in the latitude and longitude of the first one received. Did this fail for you?

**Comment by haslinger** [comment]
@ramonh regarding using the first geo-coords: I didn't notice this (though it works fine). Mostly because we redirect to the ngo events list after creating one. I now added the map to the ngo events show view. I think I have something to do there next week.

**Comment by haslinger** [comment]
Thanks, @ramonh (who did all the stuff I mentioned above.)

**Comment by ramonh** [comment]
With your help, thanks @haslinger!
