### ISSUE TITLE
Color scheme readability 

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#11]
I think it's kinda hard to read #87CEC9 on #DDDDD6 or #EDEDE5.

**Comment by klappradla** [comment]
It truly is:
![colorschema](https://cloud.githubusercontent.com/assets/3491815/10661117/475e36d6-78ac-11e5-9607-39f9d53ffdea.png)

Where is it used and how would u change it?

**Comment by markusrubey** [comment]
Currently using it on the main list for the people count. Since the text is big and bold it's not much of an issue here but still. On the detail screen i would like to use it for links as well. Currently using #00ACC1 for links.
![main](https://cloud.githubusercontent.com/assets/2398384/10662783/1b9c179c-78b7-11e5-8df4-e54ce98800aa.png)

**Comment by markusrubey** [comment]
I will come up with a improved color scheme later today, and post it here...

**Comment by markusrubey** [comment]
![color_sheme](https://cloud.githubusercontent.com/assets/2398384/10665803/03aa7a4a-78ce-11e5-904e-91c54a4ee218.jpg)

From top to bottom:
colorPrimaryLight **#43555e**
colorPrimary **#222e37**
colorBackgroundLight **#ffffff**
colorBackgroundDark **#f0f2f4**
colorAccent **#22cacf**

Would love to hear some feedback or other suggestions!

Side note: Just like the web-app i will stick to one color (colorBackgoundLight) for list items in the needs list, since scrolling gives me headaches and it interferes with touchfeedback, making darker items appear "selected".

**Comment by klappradla** [comment]
I actually didn't care bout the webapp colors yet (besides dark vs. light). So the right schema is the new one I suppose. I personally don't like the blue tone, but besides that pretty decent 💪

Someone has to adapt the logo though.

**Comment by klappradla** [comment]
So the last thing we came up was [this](https://coolors.co/002933-1f2e38-405560-00cfd2-ffffff).

![palette56687035981db](https://cloud.githubusercontent.com/assets/3491815/11694305/a25faf74-9ea9-11e5-8038-fe7766e6f57a.png)

*(again you can also get svg version, etc. via the link)*

**Comment by klappradla** [comment]
And just for the record:
- [ ] we use [this](https://www.google.com/design/icons/#ic_bookmark_border) icon *(bookmark)* for the needs a volunteer signed up to
- [ ] the icon font I use: [Font Awesome](https://fortawesome.github.io/Font-Awesome/)

**Comment by markusrubey** [comment]
I think I'll use the filled version, because the bordered one might convey an "unselected" state to the user.

**Comment by klappradla** [comment]
No worries. As we said, as long as the icon still somehow resembles the icon on the other platforms it can just be adapted to better suit the platform.

**Comment by klappradla** [comment]
Ok, the light gray still sucks... Have to think about an even lighter version of this...

**Comment by markusrubey** [comment]
I would say 00CFD2 could be seen as final. Looking at it on my phone, the first seems a little bit too greenish to me. Maybe go with the second one and darken/lighten it up to get three different versions out of it? I'll play around later today.

**Comment by klappradla** [comment]
Ok, I'm not too convinced about this color either. I now used it for all blue tones (have a look at the [staging](https://staging-where2help.herokuapp.com/?locale=de) App.

**Comment by markusrubey** [comment]
I matched the first color more with the second one and lighted up the third one a bit, resulting in: https://coolors.co/app/17252c-1f2e38-7495a9-00cfd2-ffffff
![palette56689f4a6ad62](https://cloud.githubusercontent.com/assets/2398384/11699632/92f6f670-9ec5-11e5-954f-800ebc30531f.png)

**Comment by klappradla** [comment]
Ok, so you more or less took the blue out of the first one? That's how it looks on my screen now ;) But got Flux running... so maybe it's different. I will update my colors according to this later and deploy it to Staging.

**Comment by markusrubey** [comment]
I took the second one and made it darker and lighter (in photoshop). Since I don't have a use case for the light grey feel free to change it to your needs. I might use the second one on top of the first one, so those should play well together. Still a little green on my phone though.

**Comment by markusrubey** [comment]
My eyes hurt ;) I trying to get away from the green:
https://coolors.co/app/17232a-1e2d38-7293a6-00c6d2-ffffff
![palette5668a5313bbab](https://cloud.githubusercontent.com/assets/2398384/11700275/2c46156a-9ec9-11e5-90d6-2ba854cc3c3e.png)

**Comment by klappradla** [comment]
I just updated my colors to the previous ones. You did an awesome job there on the third color (light gray) - works really well for my menus 👌
So if you don't depend on it, maybe put it back into the last update?

**Comment by markusrubey** [comment]
Alright let's go with it. Enough nitpicking!

**Comment by klappradla** [comment]
Sorry, got confused 😇
U ditched the blue from the last update? Also works like charm for me ✌️
This would be what I'm currently running: https://coolors.co/app/17252c-1f2e38-7495a9-00c6d2-ffffff

**Comment by markusrubey** [comment]
Oh, sorry! thought your where happy with https://coolors.co/app/17252c-1f2e38-7495a9-00cfd2-ffffff and deleted the newest. I like both, 00c6d2 is just a little bit more blueish.

**Comment by klappradla** [comment]
00c6d2 🤘

**Comment by markusrubey** [comment]
And the winner is: https://coolors.co/app/17252c-1f2e38-7495a9-00c6d2-ffffff

![palette5668a96f38483](https://cloud.githubusercontent.com/assets/2398384/11700689/9a7b60b0-9ecb-11e5-8b05-e7cbb4eaa405.png)
