### ISSUE TITLE
Make items in NGOs event lists more userfriendly

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#111]
NGOs have a list view for their own events. They can click on an event to view it, or use the respective buttons to directly edit or delete it. The item displays an event's description, it's address and a calendar icon for the day of the event.

**Link**
Currently both, the icon and the rest of the text are two separate links both leading to viewing an event. This could be handled more consistent, by either:
- including both items in **one** single link
- removing the link and instead adding an *intuitive* button to view the event
- coming up with an even better solution

**Formatting**
Currently both, the event description and its address are just printed out as one single line - not very readable and not very pretty. One idea could be to swap the description for the event's **title**, which is probably more meaningful for the NGO. Second, the line could use a break (resembling the view for helpers) - or again come up with an even better solution *(have a look at the schema to see what data is available)*.

![screen shot 2016-05-11 at 20 08 46](https://cloud.githubusercontent.com/assets/3491815/15223177/668d81e4-1873-11e6-978a-63d06ca4325f.png)

**Comment by klappradla** [comment]
**Bonus:** display the time (begin first shift, end last shift)

**Comment by haslinger** [comment]
@klappradla did that already!
