### ISSUE TITLE
Fix password-forgotten workflow

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#115]
**Translation / views**
The whole workflows - including both, web views as well as emails - for recovering a user's or NGO's password are not auto-translated to either German or English.
This should be fixed!

As an orientation, you can look at other [Devise](https://github.com/plataformatec/devise)- and registration-related views (e.g. user registration, user login, ngo registration, ngo login).

**UI / Form**
The forms (both for NGOs and Helpers) also lack the proper styling ([Bootflat](http://bootflat.github.io/), [Bootstrap](http://getbootstrap.com/)) in order to resemble the other forms related to login and registration.

**current state**
![screen shot 2016-05-12 at 20 23 04](https://cloud.githubusercontent.com/assets/3491815/15225687/bdad0a9c-187f-11e6-8ab3-b4050f2feeaf.png)

**Comment by haslinger** [comment]
Translated (the second part of the workflow will be handled via #143.
