### ISSUE TITLE
Fix resend confirmation instructions

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#116]
**Translation / views**
The whole workflows - including both, web views as well as emails - for resending the confirmation link for users or NGOs are not auto-translated to either German or English.
This should be fixed!

As an orientation, you can look at other [Devise](https://github.com/plataformatec/devise)- and registration-related views (e.g. user registration, user login, ngo registration, ngo login).

**UI / Form**
The forms (both for NGOs and Helpers) also lack the proper styling ([Bootflat](http://bootflat.github.io/), [Bootstrap](http://getbootstrap.com/)) in order to resemble the other forms related to login and registration.

**current state**
![screen shot 2016-05-12 at 20 27 02](https://cloud.githubusercontent.com/assets/3491815/15225753/21a7a48a-1880-11e6-88ae-0ff67e4a36a1.png)

**Comment by haslinger** [comment]
views are and mail is fine now
