### ISSUE TITLE
Make opt-in page responsive

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#119]
The page displayed after a helper opts into a shift is currently not responsive *(see screenshots)* - this needs to be fixed.

![screen shot 2016-05-14 at 12 36 47](https://cloud.githubusercontent.com/assets/3491815/15267965/c0d1d8c2-19d0-11e6-89f5-d2ec698db9e5.png)
![screen shot 2016-05-14 at 12 36 51](https://cloud.githubusercontent.com/assets/3491815/15267964/c0d0a06a-19d0-11e6-820b-4743f5333041.png)

**Comment by klappradla** [comment]
As @votexx reports, the small / mobile version does not work in IE11: **`do you prefer English`** seems to overlay the content.

I don't have a Windows machine around to test *(and eventually fix)* it. Besides that I also neither have enough disk space to to poison my own machine with that stuff (Bootcamp or VM), nor do I trust any of the *"IE for Mac"* things. My personal opinion would be: if it works on mobile devices, it's fine. I don't see a huge benefit for Windows users to make their browser window as tiny as possible.

Anyways, open for discussion here.

**Comment by haslinger** [comment]
Some improvement could be made: 
We are fine now on IE11 down to resolutions of 1024x768 by adding an extra css class in  a781754 .
