### ISSUE TITLE
Navigation webapp

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#12]
The web interface still lacks proper navigation. I'd suggest a semantically different one for each user role, arranged in a classic bootstrappy way: logo (home), etc. on the left side and user specific stuff such as logout, profile, etc. in a dropdown in the right corner.

Means of navigation I think we need:

> Already referencing a data model I suggested [here](https://github.com/refugeeHackVienna/iamin/issues/9#issuecomment-149312077)

1. normal user
  * Logo/Home -> feed view
  * Termine -> list of needs a user signed in (to allow hopping out again)
  * *Dropdown*
    * Profil -> edit form to change email / telephone
    * Logout
2. ngo user
  * Logo/Home -> feed view *(allows NGOs to check if other NGO already posted request)*
  * Kalender -> calendar view
  * Events/Termine -> elaborate list view of events and needs *(should be able to see who signed up, contact volunteers)*
  * *Dropdown*
    * Profil -> edit form *(maybe photo to better identify NGO)*
    * Logout
3. admin user
  * Logo/Home -> feed view *(allows NGOs to check if other NGO already posted request)*
  * Users -> user index
  * Events -> events index
  * Events/Termine -> elaborate list view of events and needs *(should be able to see who signed up, contact volunteers)*
  * Logout

What do you think?

**Comment by haslinger** [comment]
+1

**Comment by klappradla** [comment]
Continue here: https://github.com/where2help/where2help/issues/28
