### ISSUE TITLE
Special stylesheet import for formtastic-bootstrap?

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#126]
Just came across [this](https://github.com/where2help/where2help/blob/master/app/assets/stylesheets/application.scss) by accident. Is there a reason we cannot use a normal Sass import here @haslinger ?

I don't know by heart where we use these styles, so I don't really see a difference if I change it 🙈

**Comment by klappradla** [comment]
Background: I read some articles about organizing styles and would like to apply my knowledge to w2h ✌️

**Comment by haslinger** [comment]
As usual, I don't get it. :smiley_cat:  For me, this is a normal scss import. 
We use the styles to import bootstrap, bootflat, etc.
I believe, you should loose your styling all together, if you remove them (did you clear the browser cache?).
Btw, if you blame the imports, they are (almost) all your's, besides the first one for formtastic.

And, it's just one file, we can always go back, if something breaks. Experiment with it to your :heart:'s desire.

**Comment by haslinger** [comment]
A short in person lesson tomorrow on your knowledge here would be nice!

**Comment by klappradla** [comment]
Well sorry, was not clear enough with the above text.

We don't use the asset pipeline for CSS, we use normal Sass imports in order to make use of Sass-variables, etc.

This looks like this:
```sass
...
@import 'base'
...
```

In contrast to asset-pipeline manifest style which looks like this:
````

/*
 *= require formtastic-bootstrap
 */
```

So I was wondering why one file is imported differently. Anyways, I found the respective view and just changed the import style to sass to stay consistent. Still works (but found another bug 😉 )

**Comment by haslinger** [comment]
Ah I see, I just followed the gem's installation guides blindly.

**Comment by klappradla** [comment]
Yay, alright. Closing this with my next commit 🚀
