### ISSUE TITLE
Event list breaks when no data

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#128]
The logic of adding headers to the helpers' event list introduced in 59494fe breaks the view when no data is available.

For no events, the view only renders an "sorry no data" message. But the call to the pagination-button helper actually tries to query the empty collection:

```ruby
<%= load_more_events_btn @events, last_date: @events.last.starts_at.to_date %>
```

**Comment by haslinger** [comment]
Fixed by commit 61e090
