### ISSUE TITLE
Add social share button to opt in page

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#133]
Add a social network share button to the opt in page.

**Comment by klappradla** [comment]
Added a Facebook share button in 647b17fd9a366c0367cdae4a3f928da89f8b02c1.
It makes not too much sense - especially the wording. Gonna get back to FSW about that.

**Comment by markusrubey** [comment]
I implemented open graph stories recently. If you got the preferred wording from FSW I could set things up.

**Comment by votexx** [comment]
Below the suggestions for social sharing as requested:
Wording on the opt in page: "Schau - ich bin dabei!"
Wording when/after joining and sharing an event: "Schau - ich helfe mit!"

**Comment by klappradla** [comment]
Hey @votexx, thanx for coming back to us with the wording!

I discussed the feature again yesterday with @haslinger and @ramonh and as I already said here: https://github.com/where2help/where2help/issues/133#issuecomment-224946606 it does not makes sense in its current implementation and further more, any implementation that would make sense conflicts with the planned visibility of Event- and Shift-pages.

The only pages available from the outside without being registered and logged in are the landingpage and the registration pages. URLs of pages being shared via Facebook or Twitter need to be publicly available, otherwise the tags cannot be read by the web crawler.

**Current implementation**
Since the landing page is the only reasonable publicly available page, the sharing button shares the url to the landingpage. So regardless of which Event a user shares, the shared link will always point to the landingpage and contain the same information (as I said the tags read by crawlers need to be visible).

The result is the same as just sharing the URL of the landingpage, so a wording like *"Schau - ich bin dabei!"* doesn't make sense, as it does not relate to any Event or date or time. This button could also just be on the landingpage itself.

**Reasonable implementation**
A reasonable implementation would be: share an Event's URL, including information about place and time and saying *"Schau - ich bin dabei!"*. **Problem:** in order to do so, we would need to have a second, publicly available Event page, which conflicts with our requirements regarding privacy and authentication.

Therefore, since a reasonable implementation conflicts with our other requirements, I would propose to get rid of the sharing button on the `Opt-In` page, but leave the already in place Facebook tags on the landingpage. Therefore, it would still be possible to share `where2help.wien` on Facebook or Twitter and have a nice preview.

**Comment by votexx** [comment]
Thx for the explanation - we cannot compromise the privacy. Therefore can we merge the social sharing option with the same text & content redirecting always to the landing page? _[I´m confused now - because there is the sharing button after opt-in (attending an event) and I can´t find the one on the landingpage (=Startseite?!).]_

**Comment by klappradla** [comment]
Since it's not crucial for the launch, I'll remove it for now and we can always add it back again later.

**Comment by votexx** [comment]
So for now we remove the share-button on the opt-in page to later replace it with one that redirects to the landingpage?

Can you pls tell/show me where the facebook-tag on the landingpage is?

**Comment by klappradla** [comment]
Sorry, I was referring to **directly** sharing the landingpage URL, meaning copy it from the URL bar and paste it as a Facebook status for instance. There is no dedicated button for it and I also don't see much use for it.

So what I'm going to do is: leave the tags in place, meaning people are still able to share the any URL from the application and have a decent preview with the where2help logo etc, but remove **all sharing buttons**.
