### ISSUE TITLE
Event form add placeholders

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#134]
Add placeholders to the NGOs' event form. Tell them how to use the `description` field *(e.g. which place are the volunteers supposed to meet, etc.)*

**Comment by klappradla** [comment]
As @votexx reports, placeholder are currently not translated into german *(see screenshot)*.

![screen shot 2016-06-15 at 00 00 41](https://cloud.githubusercontent.com/assets/3491815/16061286/7844a2ae-328c-11e6-8100-f8376929a25d.png)

**Comment by haslinger** [comment]
Now fixed with 2d723dd .

One of these moments, where I start to believe I'm going crazy. (Because 100% sure, I tested it).
And facepalmed when I finally found out way later, that I used key de: alongside English translation and overwrote the German one.
