### ISSUE TITLE
Need show view

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#14]
We need a need show view -> link from feed, showing description (yet to add) and map.
Static map image can be provided via Google Maps within seconds, but free contingent is limited.

**Comment by ramonh** [comment]
I can look into this

**Comment by ramonh** [comment]
Is there a wireframe I should be following for this?

**Comment by loncie** [comment]
@ramonh and @klappradla With need show view you mean sth like the detail view in the App for the Web version?

**Comment by ramonh** [comment]
Hey! I mean the detail view for the web version

**Comment by loncie** [comment]
Ok, wasn't sure if I understood correctly in the stand up :) Thanks!

**Comment by ramonh** [comment]
No probs! :)

**Comment by loncie** [comment]
We can make it very similar to the app version. 
I'd put a big map next to the info on bigger screens and move the map to the bottom on small screens.
 
![w2h_webdetail](https://cloud.githubusercontent.com/assets/15609804/11002765/2082d36e-84af-11e5-9cbf-e97a67933f77.png)

**Comment by ramonh** [comment]
Seems doable! :+1:

**Comment by klappradla** [comment]
I will dig into this hopefully tomorrow @ramonh in order to wire up the button, etc. Ok?

**Comment by ramonh** [comment]
Ok sure, you mean the 'Ich helfe' button, rigth

**Comment by ramonh** [comment]
Resolved as of 6715811 - Although granted, we need to add fields for the NGO names and websites

**Comment by ramonh** [comment]
I'll open an issue for this
