### ISSUE TITLE
Email enumeration vulnerability

### ISSUE THREAD

**Issue by groe** [where2help/where2help#144]
When entering a valid, registered email address to password reset form responds with "Sie erhalten in wenigen Minuten eine E-Mail mit der Anleitung, wie Sie Ihr Passwort zurücksetzen können.".
When entering a wrong one it says "E-Mail nicht gefunden".

This allows an attacker/bot to brute force the form and get a list of all/many signed up email addresses. The list can be used to send SPAM to users, trick them into very targeted phishing forms, or use it for other privacy violating purposes (imagine an attacker who is against the goals of the where2help project). Also, a list of valid usernames/emails is a good starting point for password brute forcing.

More on this attack vector from [OWASP](https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)).

This can be solved by **always** responding with a vague message like "Es wird nach einem Account für die angegebene Email-Adresse gesucht. Wenn ein Account mit dieser Adresse existiert, erhalten Sie in wenigen Minuten eine Email an die angegebene Adresse."

If that's not an option, adding a captcha would also make brute forcing much harder.

**Comment by haslinger** [comment]
Both messages are just text strings we can change to your desire.
Please come back with the definitive messages in German and English you want to see here.

**Comment by groe** [comment]
@haslinger The error message is displayed as a red error-alert and the success message as a blue info-alert. Also, on success the user is redirected to the login page.

To fix this, both cases must be indistinguishable, which is not only a matter of the strings.

Maybe devise even offers an option for that? Otherwise overriding the controller should work. If you want, I can look into it as well.

**Comment by haslinger** [comment]
We can override error messages at the `devise_error_messages!` level in [devise_helper.rb](https://github.com/plataformatec/devise/blob/master/app/helpers/devise_helper.rb), and the redirect on controller level.
So what are the message texts and do you prefer the redirect to login screen or should the user stay on the page?

**Comment by groe** [comment]
I would prefer to always redirect to login.

The following strings should be fine I think:
* Es wird nach einem Account für die angegebene Email-Adresse gesucht. Wenn ein Account mit dieser Adresse existiert, erhalten Sie in wenigen Minuten eine Email an die angegebene Adresse.
* Searching for an account with the given email address. If an account with this address exists, you will receive an email to the given address in the next few minutes.

**Comment by klappradla** [comment]
@haslinger (cc @groe)

Please update the German string to
> Es wird nach einem Account für die angegebene Email-Adresse gesucht. Wenn ein Account mit dieser Adresse existiert, erhältst Du in wenigen Minuten eine Email an die angegebene Adresse.

To stay consistent with "Du" all over the platform.

**Comment by haslinger** [comment]
Note to self: All the devise translation are currently formal "Sie" and should be changed to "Du".

**Comment by haslinger** [comment]
@groe You were right in the beginning. It is an option in devise, it is called "paranoid mode"
```config.paranoid = true```
It behaves like you specced (so same message and always redirecting).
Next step will be trranslating strings from "Sie" to "Du".

**Comment by haslinger** [comment]
I now changed the API in the same  sense, i.e. providing the same error code and message for the different cases.

**Comment by haslinger** [comment]
Now in place for both systems.

**Comment by groe** [comment]
Thanks, @haslinger :+1:

**Comment by groe** [comment]
@haslinger Is this already on master? I just checked [Api::V1::UsersController](https://github.com/where2help/where2help/blob/master/app/controllers/api/v1/users_controller.rb) and noticed that `#send_reset` and `#resend_confirmation` still return JSON errors if the email does not exist. Am I missing something?

**Comment by haslinger** [comment]
Oh, my bad! I only changed the login responses. @groe thanks for double checking!

@markusrubey password send_reset and resend_confirmation now send the same json response
`render json: {password_reset: "maybe"}, status: :ok`
no matter, if a known email has been provided or not (for security reasons - explained in details above).

**Comment by groe** [comment]
Thank you @haslinger!
