### ISSUE TITLE
Landing page not displaying correctly on phones

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#145]
The landing page's icon list is cut off on iPhone 5. See screenshot:

![screen shot 2016-06-16 at 13 56 54](https://cloud.githubusercontent.com/assets/3491815/16115940/5f0bc1c0-33ca-11e6-8816-821bea2765b9.png)

**Comment by votexx** [comment]
As encouraged, I´m trying to participate directly:
Having troubles with the landing page as well (Windows Phone 8.1 with IE11):
- overlay
- logo size
![wp_ss_20160617_0001](https://cloud.githubusercontent.com/assets/19605344/16151858/520c8a4c-349f-11e6-9af7-d6cddf691432.jpg)
![wp_ss_20160617_0002](https://cloud.githubusercontent.com/assets/19605344/16151859/520e55ac-349f-11e6-8e7d-285a11ea9be5.jpg)

**Comment by klappradla** [comment]
Oh, thanx a lot @votexx! Would not have imaged it to be so bad 🙈 
Seems like IE11 is not capable of SVG...?

**Comment by klappradla** [comment]
So the Logo is now fixed for IE. But since there are just no sane possibilities in getting the footer to work on mobile IE11, I *"fixed"* it, by not not displaying it on these devices at all 🙈
