### ISSUE TITLE
Locale parameter not validated

### ISSUE THREAD

**Issue by groe** [where2help/where2help#147]
When the `locale` parameter is set to anything but `de` or `en`, the request fails with HTTP status `500 Internal Server Error`. This status code is meant for when something internally goes wrong, not when the user has submitted an invalid input value. As a result, for instance, exception notification gems or log monitoring tools often trigger alert notifications when internal server errors happen.

Can be fixed by validating the parameter before passing it to `Rails.locale` and redirecting to a valid locale or rendering a 404 error page.

**Comment by haslinger** [comment]
I will just fall back to I18n.default_locale if no available one provided.
