### ISSUE TITLE
Changing the language only works on GET-requested pages

### ISSUE THREAD

**Issue by groe** [where2help/where2help#151]
Due to how the language switcher works, it links to wrong URLs on pages that have been requested via POST, PUT etc.

1. Go to http://localhost:3000/users/password/new
2. Click "Send me password reset instructions"
3. Click "Do you prefer english?"
4. 404 page

Not ideal, but an easy fix could be to check if the current request is a GET-request and if not, link to the root URL instead:

```erb
<%= link_to(request.get? ? url_for(locale: :de, action: request.parameters['action']) : root_path(locale: :de)) do %>
  <span class="badge badge-default">Bevorzugen Sie Deutsch?</span>
<% end %>
```

**Comment by klappradla** [comment]
Interesting, thanx @groe !
We actually only need this button for the landing page and the sign up process - both scenarios where one could link to the `root_url` again....
Within the application itself, users could just set the language in their profile settings.

Any opinions on that?

**Comment by groe** [comment]
Users will usually change the language on the first page they visit anyway (before submitting any forms) - and this first request is always a GET request. So linking to the `root_url` in the edge case is totally fine IMO. The additional complexity to link to a related GET-page is probably not worth it.
