### ISSUE TITLE
User profile page lacks proper styling

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#154]
The User's (and probably also NGO's) profile page lacks proper styling:
* Buttons have to be in [bootflat](http://bootflat.github.io/) layout
* Checkboxes need to be properly nested into e.g. form groups to have the right margin and padding.

See screenshot:
![screen shot 2016-06-18 at 18 09 26](https://cloud.githubusercontent.com/assets/3491815/16172096/ce4c5f1a-3580-11e6-84aa-8b9b01e5d93b.png)

**Comment by haslinger** [comment]
Buttons now in Bootflat layout, form uses formtastic now all over the place.
I disagree regarding classes for the checkboxes, form groups are not to be used here. Styling was intentional by formtastic. I moved them to the right by 20 px to align with the headers using css.
