### ISSUE TITLE
Refactor progress-bar and ShiftsHelper

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#155]
Refactor progress-bar and `ShiftsHelper` to decrease complexity. I already have some ideas for this.

**Comment by haslinger** [comment]
Dump with message: 
`undefined method `<=' for nil:NilClass Did you mean? <=> in build_items`
line 17 of app/models/progress_bar.rb after login as NGO.

**Comment by haslinger** [comment]
Progress bar may only be shown for events with available shifts.
