### ISSUE TITLE
No explicit `dependent` behaviour defined

### ISSUE THREAD

**Issue by groe** [where2help/where2help#158]
Some associations define no `dependent: <destroy|restrict_with_error|...>` behaviour.

For instance, `Shift has_many :shifts_users`. What happens to `shift_users` when a `shift` is destroyed? They stay in the DB, right?

**Comment by klappradla** [comment]
Yes, you're totally right @groe ! I just double checked this for the `ShiftsUser`. I'll take care of this this week, thanx 4 pointing out!

Related to this: do you have an idea for a better naming of these intermediate models?

**Comment by groe** [comment]
@klappradla Thank you!

Re naming: How about `Participation` for `ShiftsUser`? And maybe `SpokenLanguage` or `LanguageAbility` for `LanguagesUser`?

**Comment by klappradla** [comment]
Nifty input, thanx! `...ation`-ending words are always very promising for these usecases! I thought about something like `helping`, but this would again lead to nasty plurals such as *"has many helpings" 🙈

**Comment by klappradla** [comment]
Interesting: automatically removing the join records on `has_many through` (what Rails 4 did afaik) seems to no longer be a default in Rails 5.

The Rails 4 docs say:
> has_many :through, where the default strategy is delete_all (delete the join records, without running their callbacks)

In Rails 5 I have to use callbacks to get the same behavior.

**Comment by klappradla** [comment]
Since this might lead to a longer discussion, I'll move the decision on better join model names to #164.
