### ISSUE TITLE
Rubocop for consistent code style?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#159]
Any opinions on [rubocop](https://github.com/bbatsov/rubocop) to maintain a consistent code style?

**Comment by klappradla** [comment]
I already thought about giving it a try. What slightly got me off this idea again though was: depending on how strong these rules are enforced, I thought it could higher the barriers for new people in the project and kinda "kill" the spirit of a community project originated in a hackathon where everyone, especially newcomers can jump in to help, give their opinions, etc. as long as they just care enough.

Still, on the long term it would probably facilitate having people of different experience levels and backgrounds working on the same codebase. And I'm kinda interested in it personally 🙈

I'd put this up for discussion then...
