### ISSUE TITLE
wrong date & time at subsequent shift

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#166]
When adding subsequent shifts and changing to a new date (24.6. 00:00 to 24.6. 02:00) the auto-count shows as follows:
![subsequent_shift_error_20160622](https://cloud.githubusercontent.com/assets/19605344/16269967/cb225350-3894-11e6-8fa4-4757a32d9f84.PNG)

can be seen [here](http://staging-where2help.herokuapp.com/ngos/events/55?locale=de)

**Comment by haslinger** [comment]
I would have never found that! It was even weirder than just the day rollover.
Fixed now. Thanks and keep them coming!
