### ISSUE TITLE
Where to report security issues once W2H is in production?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#172]
When where2help runs in production, security issues should not be discussed in public before they are fixed. Many open source projects use a separate, private communication channel for security-related reports. How about a private mailing list?

**Comment by klappradla** [comment]
Good question. I guess I'm too new school for mailing lists, neither know how they work, nor how to set them up... 🙈 
As an alternative, we could also have a locked Slack channel, or I could set up a private repository within the w2h organization (if my account has enough private ones left...)

**Comment by groe** [comment]
Aside from sporadically posting to one, I've never really worked with mailing lists either :) Creating a [Google group](https://groups.google.com) should be pretty straight forward though.

What's important is that anyone should be able to easily report vulnerabilities (without signing up etc.), but only a small group of trusted contributors should have access to the list of reported vulnerabilities. Can slack or private github repos do that?

**Comment by klappradla** [comment]
Well, both Slack and Github probably fail there. But ok, the Google Group thing seems a decent option. Do you want to go and set it up? Or maybe @votexx?

**Comment by haslinger** [comment]
When it's used in production, it should be also taken care of by the same organisation, that operates the instance.

**Comment by votexx** [comment]
Thx for bringing up the topic.
Google group it is - I´ll set one up and let you know.

**Comment by haslinger** [comment]
Google group is now in action.
