### ISSUE TITLE
Documentation does not mention .env

### ISSUE THREAD

**Issue by waldgruber** [where2help/where2help#174]
leads to setup without .env and locally changed database.yml
database.yml is NOT included in .gitignore

potential to destroy database.yml for all developers

**Comment by klappradla** [comment]
Sorry, don't really get the problem 🙈 
We're not using `.env`*(it used to be part of the project setup in the first iteration though)* with an example `database.yml`, so I don't really see a point in including the `database.yml` file in `.gitignore`. It would mean, everyone would have to set up their own...

**Comment by haslinger** [comment]
Ah, I thought it's still in use. 
So we expect to have a postgres user with username corresponding to the logged in user without any database password set but the right to create databases ... (is this correct?) 
Then this should be mentioned in the docs.

**Comment by klappradla** [comment]
Yes, that's correct. Installing Postgres automatically creates this setup.

**Comment by haslinger** [comment]
Can't confirm for Ubuntu, the only role created there is postgres (never had an issue with docker?)

**Comment by haslinger** [comment]
Yes, this should work out.

**Comment by klappradla** [comment]
So @waldgruber, try:

    rails db:drop db:setup db:populate

This should now work with default Linux setup.

If you haven't a db set up, just go with:

    rails db:setup db:populate
