### ISSUE TITLE
no registration-email

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#178]
I registered 2 users today, which are both listed in the admin-interface, but none got the verification email (after 10-15 minutes). How long does/should this take?
![w2h_registration notification_20160722](https://cloud.githubusercontent.com/assets/19605344/17060405/1f4ebba6-502a-11e6-8f76-94c4550ff659.PNG)

**Comment by haslinger** [comment]
Using the admin interface currently doesn't trigger the confirmation email to be sent. Please use the
Link to request another confirmation email or go directly to
 http://where2help.herokuapp.com/users/confirmation/new?locale=de
while I am looking into a way triggering that confirmation email from the admin interface as well.

**Comment by haslinger** [comment]
Registration emails are now also sent, when the user is created via the admin panel.
The user needs to use the password forgotten link after confirming the email address to set a password (it is not empty before, no password is set, and users without passwords cannot login).
