### ISSUE TITLE
change tab-name

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#179]
tab-name should be changed to: "where2thelp | Freiwillig für Wien" and always stay the same (if that´s not the case already)

![w2h_header_20160722](https://cloud.githubusercontent.com/assets/19605344/17060510/a7ed11e2-502a-11e6-90f4-69764e088d13.PNG)

**Comment by haslinger** [comment]
I fixed it, but there seem to be issues with the webhooks currently ... so let's wait for Github to heal again.

**Comment by haslinger** [comment]
Now it's working.
