### ISSUE TITLE
Rename "production" to staging, add new "production" config?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#187]
Since `config/environments/production.rb` has some sendgrid and email sender related configuration which is specific to the heroku staging environment, I was wondering if we could rename it to `staging` and use `production.rb` for the www.helfenplus.wien production site?

Alternatively how about introducing environment variables for the sendgrid and email sender configs? For sendgrid there already is `SENDGRID_USERNAME` and `SENDGRID_PASSWORD` but we might even send emails via a local MTA instead (not yet decided), which would not be possible right now, would it?

**Comment by klappradla** [comment]
Yes, makes total sense. I can add an additional environment **`staging`** if you want. And once it's there, feel free to adapt `production` to your needs. May even be able to do it tonight.

**Comment by klappradla** [comment]
Alright @groe, I changed the configuration as you suggested: I added a `staging` environment, [where2help.herokuapp](https://where2help.herokuapp.com/?locale=de) is using it. I also updated CI, to now deploy `master` as *staging* there.

So you can go ahead and tweak the configuration for `production` as you wish and use the `fsw` branch for production. `master` will from now on also stay *stable*, in the sense that the staging system won't be down :v: - besides that, it can still be more *"experimental"* than `fsw`.

**Comment by groe** [comment]
Thanks!
