### ISSUE TITLE
notification "event cancelled/changed"

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#188]
Please change the text as follows:
_Hallo [Vorname],
"[Eventname]" am [Datum] um [Uhrzeit] wurde seitens [NGO Name] abgesagt. 
Vielen Dank für Dein Engagement! Wir freuen uns auf Deinen nächsten Einsatz.
[where2help Wien](https://where2help.wien)_ 

Also, if there are changes for an event, there has to be a notification like the one above:
_Hallo [Vorname],
"[Eventname]" am [Datum] um [Uhrzeit] wurde seitens [NGO Name] geändert. 
Vielen Dank für Dein Engagement!
[where2help Wien](https://where2help.wien)_

**Comment by haslinger** [comment]
Resolved by a410e1d0b.

**Comment by haslinger** [comment]
The English text has to be changed accordingly.

**Comment by haslinger** [comment]
And added one more test, but we are still green  ;-)
