### ISSUE TITLE
ngo-profile | identifier not mandatory

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#189]
The identifier should not be mandatory, as there will be "private" organisations that may not have an ID.

**Comment by votexx** [comment]
I´m sorry...not even not mandatory -> we don´t need it at all (just causing problems with registration and authorities).

So ID can be deleted/deactivated completely.

**Comment by haslinger** [comment]
Reopening is fine in such a case. -> So the full dialog is available without switching between tickets.
Another example: We had a misunderstanding and we closed the ticket, but the issue is not resolved ...

**Comment by klappradla** [comment]
Remove special identifier column from NGO/contact model.

**Comment by ramonh** [comment]
Should be fixed as of 2286803
