### ISSUE TITLE
exceeding participants

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#194]
I joined the shift 9-11 of [the event](https://where2help.herokuapp.com/events/75?locale=de) and looked it up in my shifts displaying the following: 
![w2h_too much participants_20160905](https://cloud.githubusercontent.com/assets/19605344/18540696/c575d62e-7b20-11e6-888c-a435258d6ec2.PNG)

**Comment by klappradla** [comment]
Should be resolved once I'm done with #193 (it's already 80% done, should be finished by tomorrow - too tired now 😴 )

**Comment by klappradla** [comment]
Ok, #193 fixed this indeed (see screenshot). It's a shift requiring 2 volunteers and there are 3 participating.

![screen shot 2016-09-17 at 21 25 35](https://cloud.githubusercontent.com/assets/3491815/18610469/757be218-7d1d-11e6-8eab-adb43bae7072.png)
