### ISSUE TITLE
event-view: shifts on different days

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#198]
When an event is created, it is displayed on the day when the first shift takes place. If there are more shifts in one event (e.g. 12 shifts a day for 7 days in a row), the event is always displayed with the date of the first day. For users this is misleading.

Question: how can we make sure, that volunteers can see the actual date of shifts within an event without going into the event-details? I think we need to bring the shift-date into the event-overview somehow.

edit: a possible solution would be to show all shifts in the event-view sorted by date (if that´s not complete overkill)

**Comment by klappradla** [comment]
Not sure if I fully get the problem @votexx....

**events & shifts**
However, your last suggestion is indeed overkill and we already discussed this about 1k times. Most of the problems arising with this have to do with pondering urgency. Imagine for instance this view with an `event` starting right now and ending next week, which each `shift` 15 minutes long. When it comes to which shifts are *"urgent"*, you would probably say

>"the ones of all events within the next days"

But this huge event displayed with all shifts will push down all other events, even if they just start a minute after it. Only users clicking `view more` for like 1k times will actually come to see the other *"urgent"* events.

That's only one specific scenario, but I think you get the point why we changed the events view to how it looks now.

**date**
Both, the event icon and the event page's headline always display the day of the next *"available"* shift. *"Available"* means, it is still in the future and there are still people needed. Again, priority on what's urgent and what not. In the overview of shifts on the event's page (where people then opt into shifts), each shift has a own calendar icon displaying the **actual** day it starts (see screenshot for example):

![screen shot 2016-09-16 at 22 13 09](https://cloud.githubusercontent.com/assets/3491815/18599870/e96a17da-7c5a-11e6-9b80-94a370eceffa.png)

**Comment by klappradla** [comment]
I this solved @votexx ? Or are there still open questions?

**Comment by votexx** [comment]
Didn´t know about the algorithm - works fine. Ideally we could cumulate shifts so that we have at least one entry per event and day in the list (for the case, that an event has shifts spread on more days).

**Comment by klappradla** [comment]
Cool, thanx for coming back to this @votexx, so we can close this I guess 🎉
