### ISSUE TITLE
new event (ngo): placeholder "contact"

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#199]
The general terms and conditions state, that NGOs have to name a "person in charge" that is coordinating an event on premise and/or at least a phone-number. 

Therefore we need an additional field "contact" that is mandatory when creating an event stating the phone-number that volunteers can call (as they also provide this information for NGOs).

**Comment by klappradla** [comment]
Registering an NGO already requires an additional **`contact`** which includes a person and a mandatory email address and phone number. This information is for now never displayed to the volunteers. I'd suggest to just automatically include it on the event page or, if necessary link the NGO name on the event page to a NGO-profile page which then provides all this information.

I don't really see a point in forcing NGOs to again enter all this information every time they input an event: a) it is additional work hindering the NGOs to work efficient and have a benefit in using the platform and b) it will add 3 additional fields to the already complex event form, which again lowers its usability.

**Comment by groe** [comment]
@klappradla The reason why an additional field would be helpful is that there are actually 2 persons involved:
1. The contact person of the NGO (that's the field we currently have)
2. An on-site person from the NGOs team – this can (and does) change on a regular basis and is usually a completely different person.

The terms of conditions also describe that there is always one "person in charge" on site which should be contacted for any questions. So the additional field would in fact be helpful for the NGOs even though the form will be longer.

(Posting on behalf of Michi H.)

**Comment by haslinger** [comment]
So, I guess a 255 character string would be fine for this. But on which level?
Event or shift - which boil down to the question: can there be different persons in charge for different shifts?

**Comment by klappradla** [comment]
I'd have just put it on Event-level, but interesting question @haslinger ! @groe / @votexx can you get more info on that?
Also yes, a 255 char string should be fine. Won't be able to validate this though...

How would this look like?

    Frau Muster, 0123 123456

or

    Herr Muster herr@muster.at

or

    Max

**Comment by votexx** [comment]
Pls implement on-site person on level "Event" and format "Frau Muster, 0123 xxx".

**Comment by haslinger** [comment]
Implemented.
