### ISSUE TITLE
Add link to imprint

### ISSUE THREAD

**Issue by groe** [where2help/where2help#201]
Can we add a link "Impressum" to the footer which opens `http://fsw.at/impressum/` in a new window?

(creating this issue in behalf of michi h. from FSW)

**Comment by klappradla** [comment]
Yeah sure, I was just waiting for more information on what to put in the footer.

**Comment by votexx** [comment]
Plus another link "Kontakt" referring to "contact@where2help.wien".
Update regarding footer-content (ngo, ...) asap.

**Comment by votexx** [comment]
We have to "separate" the ngo-logos #184 and the other footer-issues (terms of use #202, contact, impressum), as the logos will not be implemented before organisations start using the tool. 

I´ll ask for the terms of use in english or how to handle this issue respectively.

**Comment by klappradla** [comment]
To sum it up: this is basically just adding an *impressum* link to the footer, pointing to `http://fsw.at/impressum/`
