### ISSUE TITLE
Add link to terms of use

### ISSUE THREAD

**Issue by groe** [where2help/where2help#202]
On the signup page for users/NGOs: Can we add a link to a page, where we can place the terms of use? (Should open in a new window)

(creating this issue in behalf of michi h. from FSW)

**Comment by klappradla** [comment]
Yes, we already have the link in place, we just don't have the terms of use, therefore did not add a page nor *"wire up"* the link yet.

Please provide the text for the terms of use (in both languages of course) and we can go ahead with this. I might even put it into a modal, to not navigate the users away from the actual signup. But it depends on the amount of text to display, we'll see.

**Comment by votexx** [comment]
The terms of use are not finished yet (some requirements regarding the insurance of volunteers is not yet submitted/agreed upon). Do you want to have the "so-far" version for implementing?
We have to ensure, that the terms of use are read by users - can we therefore use a popup where users have to scroll through and approve by clicking on "I agree" or sth. like that?

**Comment by klappradla** [comment]
Yes please @votexx the *"so-far"* version would be great to have right away!
