### ISSUE TITLE
Soft delete for users and ngos

### ISSUE THREAD

**Issue by groe** [where2help/where2help#204]
For insurance reasons it would be important to keep the personal data of users even after their account has been deleted (at least for some time?), or if they change it. How much effort would some simple kind of auditing functionality like this involve?

(creating this issue in behalf of michi h. from FSW)

**Comment by klappradla** [comment]
Yes, makes total sense! I actually though we already had this in place - maybe it was in the first iteration. I would suggest to just marking users as destroyed, same as for instance gems like [paranoia](https://github.com/rubysherpas/paranoia) do and then have a periodic rake task to throw out users with a `deleted_at` timestamp longer than 1 year ago for instance.

*"Recoding"* all changes would be possible as well, for instance using [papertrail](https://github.com/rubysherpas/paranoia). This would require an additional *"history"* page in the admin interface however and versions would of course pile up with time. 

So do you need the whole history or just soft delete?

**Comment by klappradla** [comment]
Are there any news on this @groe, in terms of **"recording all changes"** vs. **"only soft delete"**?

**Comment by votexx** [comment]
Hello, we go for "soft delete" after 1 year. thx

**Comment by klappradla** [comment]
@groe I added `whenever` and a monthly task to remove user records deleted more than one year ago in 0b32a164c3caa253b90ab865dcc9b7834663b6b5. Feel free to adapt it to your needs.

For NGOs, we already have soft delete in place - I may refactor it to also use `paranoia`, but it's fine for the moment I think.

**Comment by groe** [comment]
@klappradla Whenever is now deployed to production, i.e. it updates crontab on deployment. Thanks for pinging me on this and sorry for the late response (I'm still early enough to catch the first actual date of when the rake task could really delete anything, which is in 10 months or so :stuck_out_tongue:  )
