### ISSUE TITLE
Keep event data (1 year) + volunteers for ngo/admin

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#208]
Events must be available for 1 year including all details + participating volunteers for insurance reasons. 
Admins must be able to see all events of all ngos including participants (like "Events"-view of the ngo).

**Comment by klappradla** [comment]
Looking at this, I may actually really make sense to use [paranoia](https://github.com/rubysherpas/paranoia) for both, NGOs and Events *(it's really simple to line up dependent things there)*

What do you think @ramonh @haslinger ?

**Comment by haslinger** [comment]
Sure, go for it.
Btw, I don't see the point in destroying soft deleted data, storage space is cheap and I have seen lots of occasion where it was cool to own old data to prove somebody wrong.

**Comment by klappradla** [comment]
So the functionality is in place. However, it still looks a bit confusing in the admin interface. I'm planning to get rid of the Event's state machine, replace it with an enum or boolean and generate a dummy-state similar to how I did it [for ngos](https://github.com/where2help/where2help/blob/master/app/models/ngo.rb#L27).

After all, the admin-interface is the only place where having information on the state is actually valuable.

Still, this will probably take until the next Ruby Habits (Wednesday).
