### ISSUE TITLE
admin view: ngo-status

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#209]
The Admin-Panel "NGO" should also have the columns "created/erstellt", "bestätigt/verified", "freigeschalten/unlocked" and "gelöscht/deleted" -> basically like the "user"-panel.

This feature is also needed for insurance-reasons.

**Comment by klappradla** [comment]
This is closely related to #208. We currently don't record the time of *"freischalten"* which is probably bad for insurance reasons - I'll probably change this within fixing #208 (cc @haslinger by basically replacing the state machine with a timestamp as well).

**Comment by klappradla** [comment]
Hey @votexx, the respective data is in place now. I just did not put in the index table (too huge), but if you click on `anzeigen` (the show view), you'll have all the dates there.
