### ISSUE TITLE
Nicer update emails

### ISSUE THREAD

**Issue by metakermit** [where2help/where2help#21]
Once a $period (e.g. week - should be configurable). Collect all new needs created since the last email (maybe by using a `users_notified` property on the needs) and send an e-mail with the description of all these batched needs to all the registered users.

Organisers should have access to "send notification to volunteers about this need" for a specific need immediately in case of urgency (e.g. volunteers needed in 2 hours).

People should be able to opt out of email notifications (we don't wanna be marked as spam).

**Comment by klappradla** [comment]
Got new notification specs from FSW, closing this.
