### ISSUE TITLE
landing-page: new background-picture

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#210]
We want to replace the background-picture of the landing page with one that "represents" the actual situation in vienna. Are there some special specifications for that picture (will be provided by fsw)?

**Comment by klappradla** [comment]
The current picture is `2300 × 1523`px *(the new one slightly smaller, but should work as well)*.

Current new one:
![w2h_bg_fsw](https://cloud.githubusercontent.com/assets/3491815/19170286/1a390fa2-8c18-11e6-9ceb-5f315e8b6e26.jpg)

**Comment by votexx** [comment]
new pic (without filter)
![w2h_pic_landing page_20161007](https://cloud.githubusercontent.com/assets/19605344/19183930/faf5f124-8c7a-11e6-9b84-79cde4c19805.jpg)

**Comment by klappradla** [comment]
Yay, thanx 🎉

**Comment by where2help-fsw** [comment]
Here are some more pictures. 
![ww handelskai 033_68351](https://cloud.githubusercontent.com/assets/23118991/20791794/11788398-b7bf-11e6-8208-a4e781ec168d.jpg)
![ww handelskai 084_68365](https://cloud.githubusercontent.com/assets/23118991/20791792/11773998-b7bf-11e6-8fb6-d3f63e7f4f14.jpg)
![ww handelskai ii089_68344](https://cloud.githubusercontent.com/assets/23118991/20791793/11786af2-b7bf-11e6-9274-9d2e8da79e55.jpg)

**Comment by pferdefleisch** [comment]
I will rotate them

**Comment by pferdefleisch** [comment]
There are 4, they appear randomly on landing page. The images are smaller (50%) so they load faster, but they're still pretty big.
We might consider making them even smaller or supporting a library like http://imulus.github.io/retinajs/ to automatically switch on higher resolution.
