### ISSUE TITLE
Remove social sharing buttons

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#211]
As discussed in #133, there is no reasonable way to work with this now - removing it for the moment (and the public launch).

**Comment by votexx** [comment]
@klappradla, we had a quick look at the atm implemeted function of the social sharing at the event-page. As this feature at this page is working fine (redirecting to the landing page), we would like to have this feature in place as it is. One correction: the link has to be adopted to www.where2help.wien.

Can we do it this way?

**Comment by klappradla** [comment]
Yes, I don't know when I'll find the time to properly remove it and also take care about eventual changes to the UI and its responsiveness if the buttons are no longer there, so for the moment we could do this as an intermediate step.

As a final solution however, I'd still like to get rid of it. Having less features, but them implemented and working properly is to me personally a better state for the project than keeping compromises up to date.

**Comment by klappradla** [comment]
So I removed it. And @votexx, the link is automatically set to the right URL. So if you share `staging`, you end up with the Heroku URL, otherwise, just the other URL.
