### ISSUE TITLE
NGO's edit profile page does not allow to update Contact

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#213]
The current implementation of the NGO's edit profile page does not allow to update the associated Contact _(should be possible)_.

Things to do:
- update view to include necessary fields
- update controller to allow setting the respective attributes _(nested attributes)_

**Comment by Thrillberg** [comment]
Hello,
I am interested in contributing to this project and wanted to get started on this feature. Right off the bat, I ran into trouble with writing an RSpec test for PUT update and have not been able to get the `put` command to actually update the object. Here is my branch: https://github.com/Thrillberg/where2help/tree/ngo_edit_page_to_allow_contact_edits_213

As you can see, I'm simply trying to update the email of an NGO to "hello" for now, and it's not working. Is there something about this project that I need to know that I'm not seeing? Any help would be greatly appreciated!

**Comment by klappradla** [comment]
Hey @Thrillberg, first of all, awesome that you wanna help 🎉 💚 

Both, the project itself and the resource you're operating on are pretty *"basic"* railsy things, e.g. using Devise for authentication as you probably noticed. From quickly peeking into your fork, I guess the problem / blocker you have could just be the fact that you try to update **the email**. 
Within Devise models, this is usually one of the most difficult attributes to update. Depending on the configuration of the resource - I don't know ours for NGOs by heart now - updating the email address requires a password and respectively signing in and out the updated user / NGO.

So to just see if the general operation works, I'd suggest you try to update the NGO's `name` attribute instead. It's a non-Devise attribute, so things should be pretty straight forward there. 

Furthermore, if you take a look at Devise's [original implementation](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L44), they do different things depending on which attributes are updated.
The [wiki](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password) even has a own section about the whole update-email topic.

So as I said, just give it a try with a different attribute first. Let's see if this works.

**Comment by Thrillberg** [comment]
Thanks for the speedy response, @klappradla! And thanks for the warm welcome. I had actually been using the `name` attribute before and still got the same error. I switched it to `email` because I thought it might make a difference but it seems not to have.

I've also tried manually dropping devise's implementation into the code and sticking a byebug in there to find out what went wrong. It turns out `account_update_params` is not working because the sanitizer isn't working. But I don't really know where to go from there.

**Comment by haslinger** [comment]
Interesting. Currently not at home. Will look into this tomorrow. And welcome @Thrillberg!

**Comment by Thrillberg** [comment]
Thanks @haslinger! Let me know when you get a chance to look into it. I'm very excited about contributing.

**Comment by haslinger** [comment]
@Thrillberg You left out the current password in your PUT request, which is required by Devise.

**Comment by ramonh** [comment]
Just wanted to thank you for helping as well @Thrillberg 🚀

**Comment by Thrillberg** [comment]
@haslinger Hmm, I tried putting `current_password: ngo.password` in the params like so:
`{id: ngo, ngo: {name: "hello", current_password: ngo.password}}`
and in the PUT request like so:
`put :update, params: params.merge({current_password: ngo.password})`
and it still won't assign the name to "hello".

**Comment by haslinger** [comment]
@Thrillberg 
The code in your branch shows neither of these changes.
The update params should not contain an id, the request changes the data of the ngo logged in.
What is the response code of the request, what the error messages, if any?

**Comment by Thrillberg** [comment]
@haslinger Thanks for the help. I've figured it out (I think) and proceeded to implement the whole feature. I've put up a PR; let me know if there's anything further I should do/change on this point.

**Comment by klappradla** [comment]
Closing this thanx to @Thrillberg 🎉

**Comment by Thrillberg** [comment]
Thanks @klappradla!!!
