### ISSUE TITLE
Admin Event View

### ISSUE THREAD

**Issue by where2help-fsw** [where2help/where2help#219]
![w2h_adminview](https://cloud.githubusercontent.com/assets/23118991/19836968/010908d4-9eb0-11e6-8130-7d352dc59c51.png)

Here is a volunteer in the ADMIN event view, but "0" commitments. Has he logged on and logged off?

**Comment by klappradla** [comment]
Ah, thanx @where2help-fsw ! Can be calculation problem or pulling in the wrong data... We'll have to investigate 😉

**Comment by haslinger** [comment]
Looked into this, here only a counter cache is displayed. 
Checked the actions in question, they update the counter cache properly.
So actually no clue, how this can happen.

Next step would be resetting the counter cache:
`Event.reset_counters(put_in_id_here, :volunteers_count)`.
Does this help, @groe or @pferdefleisch ?

**Comment by groe** [comment]
Thanks @haslinger for looking into it. I think the `volunteers_count` displayed in the screenshot is from a shift-model, not an event. However, `Shift.reset_counters(19, :volunteers_count)` raised `ArgumentError: 'Shift' has no association called 'volunteers_count'`.

That shift currently has 3 participations (deleted_at is nil for all of them, and also for all of the users), but `volunteers_count` is 2:

![image](https://cloud.githubusercontent.com/assets/515293/20221309/202b299c-a831-11e6-897d-54a516ded5e6.png)

Any ideas?

**Comment by klappradla** [comment]
From what I remember @groe , the correct syntax is 
```ruby
Shift.reset_counters(19, :volunteers)
```
The *_count*-part makes it invalid, the error is actually pointing you in the right direction 😉

**Comment by groe** [comment]
@klappradla Ah, you're right, it expects the association name (and thats `:participations`, not `:volunteers`). I just tried it locally and it worked - will run it in production soon as well.

Really strange how the counter cache got out of sync with the actual count.

**Comment by klappradla** [comment]
Ah, sorry, sure `participantion` 🙈  - I renamed it myself because I thought it was not expressive enough 😂

**Comment by groe** [comment]
Fixed the outdated cache in production.

Closing this issue for now. If it reoccurs, feel free to open another issue (or post a comment). Any ideas how the counter cache could have gotten out of sync are welcome!
