### ISSUE TITLE
(Interactive) Wireframes for user workflows

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#22]
This is mostly brainstorming

- [ ] ngo workflow story
- [ ] ngo creating need
- [ ] ngo editing need
- [ ] ngo looking at need status
- [ ] ngo deleting need (and how does this affect volunteers)

- [ ] volunteer looking at needs
- [ ] volunteer filterning at needs
- [ ] volunteer signing up for need
- [ ] volunteer canceling need
- [ ] volunteer looking at needs they are part of
- [ ] volunteer need history

**Comment by klappradla** [comment]
Closing this as too old, since we redefined the MVP anyways.
