### ISSUE TITLE
Reset password link not working for NGOs

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#220]
Devise's reset password functionality seems not to be working for NGOs *(for volunteers it seems to work)* - at least on production.

**Comment by pferdefleisch** [comment]
What's happening? Is there an exception? Is the email just not getting sent?
--
bussi,
aaron :sunglasses:

**Comment by groe** [comment]
@pferdefleisch I just tried it in development and got this exception:

```
NoMethodError at /ngos/password
private method `confirmed?' called for #<Ngo:0x007f7e3eac1070>
Did you mean?  confirmed_at?
```

**Comment by pferdefleisch** [comment]
I just fixed it, pushing in a minute

I'm also adding the letter_opener gem so we can look at emails in a browser tab

if @klappradla @ramonh @haslinger have an issue, let me know. There aren't a ton of gems and i don't plan on dumping a bunch in here.

**Comment by groe** [comment]
Thanks!

Re letter_opener: #149

**Comment by pferdefleisch** [comment]
Great. thanks @groe
