### ISSUE TITLE
Misleading timestamps in volunteers' event list

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#224]
The timestamps on the event list for volunteers are slightly misleading: they only display the timespan of the **first shift**, even if the event has **multiple shifts available**. If this is not a feature *(I honestly cannot remember 🙈  )* then I'd prefer to show the whole timespan, starting from `starts_at` of the first and ending at `ends_at` of the last available shift.

![screen shot 2016-11-07 at 23 19 35](https://cloud.githubusercontent.com/assets/3491815/20078492/1ec81058-a541-11e6-8892-c09149312efa.png)

**Comment by groe** [comment]
How about showing:

*  `14:00 - 16:00` if there is 1 shift on the same day
*  `14:00 - 16:00 und 16:00-18:00` if there are 2 shifts on the same day
*  `14:00 - 16:00, 16:00-18:00 und N weitere ` if there are 3 ore more shifts on the same day

**Comment by klappradla** [comment]
Oh, nice idea @groe, thanx 👍 
I'll have a look if this does not exceed helper complexity and available space in the view. Guess it probably won't though.

**Comment by haslinger** [comment]
Just for clarification: Currently it displays the start time of the first available shift and the end time of the last available shift:
`available_shifts.last.try(:ends_at)`

**Comment by haslinger** [comment]
OK, so I had to change the witth_available_shifts that actually destroys the relation (not the group_by).
But this way kaminari is broken - but can be fixed by converting to an array on controller level.

**Comment by haslinger** [comment]
fixed by 5bae1e3
