### ISSUE TITLE
For every day, show all events that have shifts on that day, that have not ended yet

### ISSUE THREAD

**Issue by groe** [where2help/where2help#225]
Right now the events list contains every event only once, based on the date of its first shift beginning date that is still in the future.

In production this has caused two problems:

- [x] Shifts that have already started are hidden instantly (although the NGO might still be searching for volunteers during the shift)
- [ ] Volunteers often plan ahead a few days, e.g. they want to see where they can help on the next weekend. So they look at the date for the weekend but it's either empty or many events that have shifts on that date are not included on the list (because they are listed somewhere above on an earlier date).

Proposal:

1. **Hide events in the "Today" date group after they have ended**, instead of after they began.
2. **For every day, show all events with all shifts on that day** (i.e. group by date first, then group the shifts of event). So if one event has multiple shifts on the same day, it's listed once. But if it has shifts on two days, it's listed twice.

Ad 2: This will make the list much longer but I think it's worth it because the "Look up a date and see where I can help on that date" use case is so important. For performance we might have to look into pagination or caching (later), but I would keep it simple for now and see if we run into any problems. One thing we can do is **limit the list to dates in the next 4 weeks**.

**Comment by klappradla** [comment]
Oh, nice *"real world experience"*-feedback, thanx @groe ! We did not really think about these cases...

The code driving the list, especially the db query and the logic to correctly set the "day"-headlines via javascript is a bit hacky and we went back and forth for quite some time to get it right 😉  A major problem usually was the **order** of events: it needs to be deterministic in order for the pagination to work... 

Your idea sounds pretty decent! Let me know if you need some help / insights into either the query on the JS hacks.
