### ISSUE TITLE
Renaming repository to where2help

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#23]
I would love to see this particular repository to be renamed to where2help. 
I believe it is the last naming inconsistency related to the project's old name.
Any opponents?

**Comment by klappradla** [comment]
I'm so with u on this 👍
Can u rename the whole rails app, too? I did it once, but cannot remember the amount of hassle for it...

**Comment by ramonh** [comment]
I'm 100% in agreement.

Can I go ahead or would that step on toes?

**Comment by haslinger** [comment]
I think it's not too bad. There are some references to it in css classes, that I wouldn't touch, so it pretty much boils down to changing the module name in application.rb
Fill text search for iamin can be your friend here.

**Comment by haslinger** [comment]
@ramonh Everybody has to change his/her remotes in git. So a note after changing in the dev slack would be nice.

**Comment by ramonh** [comment]
Yep sounds reasonable. I'll go ahead and start on this, then

**Comment by ramonh** [comment]
@haslinger I've partially resolved this, and will start renaming the rails app

**Comment by klappradla** [comment]
Continue here: https://github.com/where2help/where2help/issues/28
