### ISSUE TITLE
Replace images on signup forms with new ones from FSW

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#231]
I'll replace the green-overlayed images using in the application with new ones from FSW, resembling the one on the landing page and the current scope of the app's volunteer work fields.

**Comment by klappradla** [comment]
Changed the images to be more resemble the one from the landing page. However @groe and @pferdefleisch, in lack of alternatives I had to reuse the one from the landing page again. Would be cool if FSW would provide more images soon. We already have some [here](https://github.com/where2help/creative/tree/master/images/fsw) but the third one does a) not have as good quality and b) does simple not look as nice.

**Comment by pferdefleisch** [comment]
Should we create a new issue to get the images and assign @where2help-fsw?

**Comment by klappradla** [comment]
Well, they should know it already, but yeah, go for it! Good to have a reminder there ⏲
