### ISSUE TITLE
Admin Dashboard Statistics

### ISSUE THREAD

**Issue by groe** [where2help/where2help#233]
Some basic statistics in the admin dashboard would be helpful, like:

* event count
* total participations count for all shifts/events
* total sum of required volunteers for all shifts/events
* total sum of volunteer work hours that have been organized through w2h

**Comment by pferdefleisch** [comment]
@groe 
> total participations count for all shifts/events
Is this in the future or all time? Or both?

**Comment by pferdefleisch** [comment]
I decided to do both separate.

> total sum of volunteer work hours that have been organized through w2h

Does this count the upcoming?
