### ISSUE TITLE
Lock user accounts

### ISSUE THREAD

**Issue by groe** [where2help/where2help#237]
It should be possible to lock a volunteers user account to disable further logins from this account.

Use case: Prevent abuse of the system, spam, etc.

**Comment by klappradla** [comment]
Makes sense. Should also be pretty straight forward, [Devise](https://github.com/plataformatec/devise) has a module for this already: `Lockable` afaik.

**Comment by haslinger** [comment]
To play devils advocate, it's takes a troll a minute to create a new account...

**Comment by klappradla** [comment]
Sure @haslinger! But it could still come in handy as an alternative to deleting a user's account - since this would a) free up her email address again and b) make it harder to keep track of the *"bad"* users who have been blocked. So I think it's a good idea to introduce this devise module.

**Comment by haslinger** [comment]
Sure, I didn't intend to oppose devise/lockable, I just wanted to lower the expectations of the outcome. 
I was thinking more of setting a fake password - but using lockable is better, as it's more obvious for admins, which accounts are locked on purpose.
