### ISSUE TITLE
Is there a use case for an "All" events filter for NGO's?

### ISSUE THREAD

**Issue by mraaroncruz** [where2help/where2help#239]
I think an improved UX for the ngo events list would be tabs.
| Zukuenftige | Vergangene | (if answer is yes) Alle |

Which would default to Zukuenftige because I think that is the most interesting info for the NGO (let me know if I'm wrong here).

Scrolling down to the bottom of a maybe long list to see other information that may not be interesting seems strange to me.

**Comment by klappradla** [comment]
No, I don't see the use case, 👍  for skipping it. I also really prefer a 2-tabbed view to one with 3 - just way cleaner.

Also, defaulting to future ones, for sure 👍  go for it 🤖

**Comment by pferdefleisch** [comment]
Also waiting for feedback from @where2help-fsw

**Comment by groe** [comment]
@pferdefleisch Is this still issue still relevant? We changed the UI quite a bit and I think "All" is now a filter option in a dropdown (which makes sense to me).

**Comment by groe** [comment]
Closing this.

@mraaroncruz @klappradla Feel free to reopen if it's still relevant.
