### ISSUE TITLE
Add Past Events and Volunteers counts to Populate

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#240]
The data could be more realistic. Some stats for example aren't working.

**Comment by klappradla** [comment]
Makes total sense - feel free to adapt the populate script.

Just take care: for fully deleting deleting records, either just drop the DB (shortcut version) or go with
```ruby
records.unscoped.map(&:really_destroy!)
```
Again, because of `paranoia` and soft delete things.

**Comment by pferdefleisch** [comment]
I will update when I also add ongoing events when #223 is done

**Comment by pferdefleisch** [comment]
It's really called `really_destroy!`? That's awesome.
