### ISSUE TITLE
User Onboarding/Flow

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#25]
The following pic shows the current user flow of the android app:
![android_onboarding](https://cloud.githubusercontent.com/assets/2398384/10634055/51b1a946-77ef-11e5-96fa-c1be09c874e3.jpg)

But maybe we should force a user login/register on startup just like the web app since needs are not public anymore.

**Comment by haslinger** [comment]
You probably have to because you have to create a user before receiving data in the current version of the API. See documentation: https://github.com/refugeeHackVienna/where2help/wiki/API 
Seems I did a really bad job on communication here. Sorry for that.

**Comment by markusrubey** [comment]
@haslinger talking to the backend is implemented as documented, just need to get the UI flow right. 

/auth documentation is pretty nice! I would love some more details on the /volunteerings end. I would like to list all the needs the user is attending to inside the user profile.

**Comment by haslinger** [comment]
Cool. I take the API part with me into #26.

**Comment by markusrubey** [comment]
Alright, i'm going to switch things up to something like this:
![where2help_flow](https://cloud.githubusercontent.com/assets/2398384/10636274/fe62312e-77fe-11e5-8533-7b7e90007e6c.jpg)

**Comment by pferdefleisch** [comment]
I don't think we should base our user workflow on how things are right now. It is a very important decision whether the user has to log in before doing anything.

I think that the first workflow is better. Lower barrier of entry.

But there are things to be said for the latter, like maybe a user will download the app, see there aren't any matching needs and then never open the app again. Forcing them to log in may make them available to receive updates for needs they can sign up for in the future.

**Comment by markusrubey** [comment]
Good points! As mentioned on slack, it's also easier to implement, since i don't have to decide between has-user an no-user all the time. At one point the user is stuck anyways. I think people these days are pretty used to signups on fresh installed apps. 

I agree that keeping a lower barrier of entry should be a goal. Which is why I won't ask for first-name, last-name, phone, ... just email and password. (Maybe implement the google-sign-in-button one day)

More importantly for the user: It should be made clear why a login is necessary and what features it enables so he or she can make sense of it.

**Comment by pferdefleisch** [comment]
I agree with your last point, though I don't agree that users are used to signing in these days. I have seen lots of people say "Uhhh, nope" or said straight up "I shouldn't have to do this" when asked for immediate login.

But I think in our case, people want to help so it won't bug them as much if we explain why. So let's go with the second workflow!

You can close the issue if there's nothing more you need here.

**Comment by markusrubey** [comment]
I'm not happy with the results on this. Would appreciate more input from others as well.

The more i think about it i tend to agree more and more with aaron. 

Another issue i just realized,which is linked to this one, is if a user shares a need with others. They follow the shared link and will be stuck on the login/register screen. That's no good...

**Comment by pferdefleisch** [comment]
I didn't think of that... good point.

**Comment by klappradla** [comment]
@markusrubey good point! I partly thought of it when preparing the single need route and view for volunteers.
Is opening the list view + single need view to non-signed in users and then requiring login upon trying to sign up for a need a reasonable solution for u on mobile, too? (I still need to add friendly forwarding anyways #18 )

**Comment by markusrubey** [comment]
@klappradla Yep, sounds good. I think showing a sign-up/sign-in popup for the "i'm in"-button and a popup if the user want's to see his profile (screenshot upper right) will do it. And on the first startup maybe a little tutorial which is skippable to make clear to the user that you should sign-up and press "i'm in" if you want to help.
![device-2015-11-02-123744](https://cloud.githubusercontent.com/assets/2398384/10880943/4b421022-815f-11e5-94ee-438b5393c346.png)

**Comment by klappradla** [comment]
Yes for 95%. Popups are not the way to go on the web interface - they are fuckin annoying and most browers block them anyways. So for the web interface I'd go with a straight redirect to the signup showing a notice telling that login is required. After sign_up / login the user will be again forwarded to the page where she was before.

If popups is best practise on mobile, stick with it. I just think we should keep the general workflow in sync.

**Comment by markusrubey** [comment]
I agree. Everyone should stick to his platform's design patterns but the overall flow should be the same.

**Comment by klappradla** [comment]
Ok. I'll think about it for like another 30 minutes / finish the stuff I'm currently working on and add a MVP feature then.

**Comment by markusrubey** [comment]
Alright :thumbsup:

**Comment by klappradla** [comment]
For webapp, continue here: #38

**Comment by markusrubey** [comment]
For android, 10 and 11
