### ISSUE TITLE
Send out emails on participation

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#250]
We need to decide whether we want to send out an email on participation to:

1. inform NGO about volunteer
2. give volunteer a confirmation in his email inbox to remind him

This question is being pushed upstream but if the answer is yes, we will need translations for any needed emails.

**Comment by pferdefleisch** [comment]
@groe have you spoken with FSW about this? I'd love to close it.

**Comment by groe** [comment]
@pferdefleisch We ran out of time unfortunately, so we haven't discussed it yet

**Comment by pferdefleisch** [comment]
It's not urgent so just be aware and look at all the discussion issues before meetings.

**Comment by groe** [comment]
Will do. Next meeting is on Jan 12.

**Comment by groe** [comment]
FSW says: For now we only need one email notification and that is when a volunteer signs up for an ongoing event, W2H should notify the NGO about that. (Only for ongoing events, not for scheduled ones.)

It is important that the email does not contain the actual personal data of the volunteer but rather a link to it within W2H.
