### ISSUE TITLE
For ongoing events, there should be progress bars as well

### ISSUE THREAD

**Issue by groe** [where2help/where2help#251]

**Comment by pferdefleisch** [comment]
Just on the NGO side, right? @groe

**Comment by groe** [comment]
No, for volunteers as well. (Or is there a specific reason why that would
be a bad idea?)

Aaron Cruz <notifications@github.com> schrieb am Di., 6. Dez. 2016, 19:36:

**Comment by pferdefleisch** [comment]
The count is just for bookkeeping. More than the max volunteers can sign up. So it wouldn't make sense on the volunteer side. This is also why I questioned it even being on the NGO side.

**Comment by groe** [comment]
Antonia said "overbooking" is fine and the progress bar (1) makes the site visually more appealing and (2) is actually an interesting information for volunteers ("Should I sign up for the activity that already has 40 out of 50 volunteers or for the one with 0 out of 20?").

**Comment by pferdefleisch** [comment]
Hah! This progress bar is the most complex part of the system. I love it. When you pull out `to_partial_path` you're not messing around :sign_of_horns: cc @klappradla

**Comment by pferdefleisch** [comment]
@groe What is the expected behavior of a volunteer seeing an ongoing event in the list where they are signed up? I think they should see "You're registered" or something. You can add a new issue

**Comment by klappradla** [comment]
Haha @pferdefleisch 😗  the progress bar is indeed a monster - but I kinda liked it. It was a single helper method before I refactored it into what it is now ✌️ 
What do you mean with pulling out `to_partial_path`? Is there a neater way to do this?

**Comment by pferdefleisch** [comment]
@klappradla I was commenting on the rails hacking. I don't see much of this and it's nice to see.
I don't think there is a neater way.
I would have exposed some kind of helper function or class.
Just Rails way vs. non-Rails way.

I guess there is one way to make it neater. The naming is pretty generic (ie `Item`) and could be more descriptive. Like, what is an offset? I had to do some deep diving to figure out what was going on there.

**Comment by klappradla** [comment]
Oh, there you're definitely right, the "algorithms" could be way more explicit. I had a hard time understanding them as well. As I said just refactored all this out of a single helper function, so this could probably have another round of refactoring, now that it's "real" ruby code.... 😉
