### ISSUE TITLE
The ongoing event list should be striped

### ISSUE THREAD

**Issue by groe** [where2help/where2help#252]
We are thinking about adding categories for ongoing events (e.g. "teaching", "transportation", etc.), but we are still working on the exact spec.

In the meantime, could we make the ongoing event list striped, i.e. each line cycled white/gray?

**Comment by groe** [comment]
Extra points for this CSS:
* Lines that are already gray should become even darker on `:hover`

**Comment by pferdefleisch** [comment]
@groe I didn't make it darker but it is darker than the stripe. Give it a look and let me know.

**Comment by groe** [comment]
@pferdefleisch Looks good!
