### ISSUE TITLE
API extension

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#26]
Documentation: More details on the /volunteerings end. 
Extending endpoint: user#show : I would like to list all the needs the user is attending to inside the user profile.

**Comment by haslinger** [comment]
User api created (but with to many actions). See https://github.com/where2help/where2help/wiki/API#users for details. Data is restricted to current user, if current user is no admin, but modifications of needs is a bad idea. I will look into this.

**Comment by markusrubey** [comment]
Fired to a couple /users/.. endpoints, just getting code:500 /play trololo

**Comment by markusrubey** [comment]
Maybe not API related because it worked once but lately i am getting CODE: 400 Bad Request from ```v1/users/:id:/relationships/volunteerings``` with a empty response.

**Comment by haslinger** [comment]
Hm, it took my quite a time to figure out correct requests and responses, but finally managed to subscribe via wget.
I documented it in https://github.com/where2help/where2help/wiki/API-Example:-Create-a-volunteering

I saw 400s as well, when I learned the hard way by debugging to format user_id as user-id in the request.
