### ISSUE TITLE
NGO events page layout

### ISSUE THREAD

**Issue by groe** [where2help/where2help#262]
A few changes to improve the NGO events page

- [ ] The segmented control should be at the top
- [ ] Both buttons to create a regular event and to create an ongoing event should be visible always
- [ ] The buttons should have a plus icon
- [ ] Depending on which section I'm in, one of the buttons should be `btn-primary`
- [ ] Looks like NGOs don't need the "sort by" dropdown (we can remove it)
- [ ] Move the filter dropdown to the right (Except on mobile, I guess?)
- [ ] Not only on this page, but actually everywhere: The contrast for the selected button in a segmented control is not ideal (white on light gray). Can we make it `#434A54` (the same as when its not selected) on light gray instead?

Here's a screenshot from a mockup of all those changes:

![bildschirmfoto von 2016-12-13 17_02_09](https://cloud.githubusercontent.com/assets/515293/21230583/c0716f5a-c2e5-11e6-928c-5dfb7e4cbe7a.png)

**Comment by pferdefleisch** [comment]
I feel pretty weird about that button UX but we can try it out at least because I don't have a better suggestion if it is necessary to have both on both pages.

**Comment by groe** [comment]
Yes I was thinking the same. I considered using a split button instead but that would hide the second option as well...
