### ISSUE TITLE
Chatbot for Facebook Messenger?

### ISSUE THREAD

**Issue by groe** [where2help/where2help#267]
A messenger bot could allow users to

* be notified about event changes (similar to emails, configurable)
* be reminded about an upcoming event the user is signed up for
* be notified about "urgent" events, with an option to opt-in via messenger
* send feedback and questions, which could be forwarded either to NGOs of events the user has signed up for or the Where2Help team (I think it's important to manage expectations here, e.g. "Thanks for you message. Forward it to [W2H] [NGO ...]? In urgent cases, please contact ... via phone.").

For Facebook Messenger we could use the [Send-to-Messenger plugin](https://developers.facebook.com/docs/messenger-platform/plugin-reference/send-to-messenger).

@pferdefleisch To discuss the idea, can you make some wireframes of how it could work from a users perspective?

**Comment by pferdefleisch** [comment]
I will set up an interactive wireframe and create a video of me describing the interactions tomorrow. 💋

**Comment by pferdefleisch** [comment]
Demo completed
