### ISSUE TITLE
Getting empty headers from /needs

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#27]
A GET to ```/api/v1/needs``` returns empty HTTP headers.

10-22 12:37:36.365 27554-28119/app.iamin.iamin E/PullNeedsTask: Access-Token = null
10-22 12:37:36.365 27554-28119/app.iamin.iamin E/PullNeedsTask: Token-Type = null
10-22 12:37:36.365 27554-28119/app.iamin.iamin E/PullNeedsTask: Client = null
10-22 12:37:36.365 27554-28119/app.iamin.iamin E/PullNeedsTask: Expiry = null
10-22 12:37:36.365 27554-28119/app.iamin.iamin E/PullNeedsTask: Uid = null

**Comment by haslinger** [comment]
The users created by the populate task where not complete in the sense, that they were missing the uid attribute.
In that sense we could create non-api users in future, if that could be useful, by not populating the uid attribute.
Now I've to get someone to push to Heroku... I'll be back.

**Comment by markusrubey** [comment]
Thanks for looking into this! Having to sign in and out every time makes things :turtle:

**Comment by markusrubey** [comment]
Seems like things got messy. 

auth/ now returns empty headers
auth/sign_in begs for headers 
web version :boom:

**Comment by haslinger** [comment]
Seems to be OK now, I tested via sign in:
```
wget http://staging-where2help.herokuapp.com/api/v1/auth/sign_in --post-data="email=normal_user@example.com&password=supersecret" -S
```
and then retrieving data: 
```
wget -S --header="Access-Token: sJsZkahsj0ru1XWep5KEtA" --header="Token-Type: Bearer" --header="Client: AoEQF_Ipb-HqKchZaC43zg" --header="Uid: normal_user@example.com" http://staging-where2help.herokuapp.com/api/v1/needs
```
and get back headers with new token as it should be:
```
 Access-Token: WYqCEjOx_AAXVS8vZyUxow
  Token-Type: Bearer
  Client: AoEQF_Ipb-HqKchZaC43zg
  Expiry: 1446737596
  Uid: normal_user@example.com
```

**Comment by markusrubey** [comment]
Login works just fine and returns

`Access-Token = zz3p0iIAS1uv8Gw4rWjVyA`
`Token-Type = Bearer`
`Client = fqPJWvsAh_CwJB87GnCddA`
`Expiry = 1446739261`
`Uid = normal_user@example.com`

but i still get empty headers back from /needs

**Comment by haslinger** [comment]
Against staging?

**Comment by markusrubey** [comment]
yep

**Comment by haslinger** [comment]
In case of properly specified headers, I always get proper response,
```
 wget -S --header="Access-Token: _tZvE0BDrUrD3j4pfNtU9A" --header="Token-Type: Bearer" --header="Client: J7LKRxSk9tdQZ7bh6_s-Zg" --header="Uid: normal_user@example.com" http://staging-where2help.herokuapp.com/api/v1/needs
--2015-10-22 19:29:11--  http://staging-where2help.herokuapp.com/api/v1/needs
Auflösen des Hostnamen »staging-where2help.herokuapp.com (staging-where2help.herokuapp.com)«... 54.163.249.29
Verbindungsaufbau zu staging-where2help.herokuapp.com (staging-where2help.herokuapp.com)|54.163.249.29|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 
  HTTP/1.1 200 OK
  Server: Cowboy
  Connection: close
  Date: Thu, 22 Oct 2015 17:29:13 GMT
  Status: 200 OK
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Access-Token: hdt7NkVqfsRU9j0NKm1ZOg
  Token-Type: Bearer
  Client: J7LKRxSk9tdQZ7bh6_s-Zg
  Expiry: 1446744553
  Uid: normal_user@example.com
  Content-Type: application/vnd.api+json
  Etag: W/"6ce2a2e658f6fa98b9fc13849fb346d3"
  Cache-Control: max-age=0, private, must-revalidate
  Set-Cookie: _session_id=ZVRpZWYwUXpzQ3ZkaUJ5KzFhSXRDVk1KbFc2MXhyOGhaZE10T2lJWUdkWGQ4NlJaMEdLL2k1WFhrNkU2V2xDZWlyZUI0U1JxOWgzR2t1dkszQ200MGt0NEo5b05YUFJKZVFabE5NdHkycGZHVk9EVEVQWGQvUFlwY24vYjNNbWxmNlpOaXh5TmZyOCtPU0xlbEUxM1ZnPT0tLUdpKzM1MzVCVGJjVVB6bW5ZTSs4VFE9PQ%3D%3D--38035f561bb7212d2100914a708c0ff0b3ffb534; path=/; HttpOnly
  X-Request-Id: a1231ad4-9703-4d4c-831d-953caf721da3
  X-Runtime: 1.598886
  Via: 1.1 vegur
Länge: nicht spezifiziert [application/vnd.api+json]
In »»needs.5«« speichern.
```
in case of wrong headers (here a wrong token)
```
wget -S --header="Access-Token: sJsZkahsj0ru1XWep5KEtA" --header="Token-Type: Bearer" --header="Client: AoEQF_Ipb-HqKchZaC43zg" --header="Uid: normal_user@example.com" http://staging-where2help.herokuapp.com/api/v1/needs
--2015-10-22 19:28:38--  http://staging-where2help.herokuapp.com/api/v1/needs
Auflösen des Hostnamen »staging-where2help.herokuapp.com (staging-where2help.herokuapp.com)«... 204.236.218.45
Verbindungsaufbau zu staging-where2help.herokuapp.com (staging-where2help.herokuapp.com)|204.236.218.45|:80... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 
  HTTP/1.1 401 Unauthorized
  Server: Cowboy
  Connection: close
  Date: Thu, 22 Oct 2015 17:28:38 GMT
  Status: 401 Unauthorized
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  Content-Type: application/json; charset=utf-8
  Cache-Control: no-cache
  X-Request-Id: be161b89-af6d-4c24-b9af-9cb6b6bc3f61
  X-Runtime: 0.089018
  Via: 1.1 vegur
```

You get a HTTP/200 response, but without token headers?

**Comment by haslinger** [comment]
I've got it. You seem to do batch requests. (Several requests with the same token.) Only the first requests sends back the new token. As long as the next requests is within 5 seconds, the request is accepted, but no new token is returned.
If you always pick up the new token and provide it in the next request, you should be fine.

**Comment by markusrubey** [comment]
oh, that might be the case, will look into it...

**Comment by markusrubey** [comment]
So strange, I don't use a token twice. i request login - get my headers - request needs with those headers - don't get any headers back. i only get code=200, message=OK and the needs.

**Comment by haslinger** [comment]
OK, I see, I need access to the logs. Will try to get it tomorrow.

**Comment by markusrubey** [comment]
Cool. I can't tell any wrongdoing on my end, maybe you don't get my headers in the first place.

**Comment by haslinger** [comment]
Meanwhile access to the logs, no logging of headers. Aaargh. Will sleep and think about it. 
Maybe Heroku is doing something strange, but not with wget, just with Android headers .... 
Trying to debug this tomorrow with my phone and local dev server. Sorry for all this hassle!

**Comment by haslinger** [comment]
Couldn't stand it. Had to debug it. And: Works for me on staging! 
I did the following:
Download the latest app, you provide in the dropbox. Login via normal_user@example.com
Login succeeds, feed is displayed correctly on my Android phone!

Just to be on the safe side: Changed one need to ridiculous 888 translators. Went out of app. Back in. Works again with properly displayed new count.

From now on the relevant headers are logged in the Heroku logs.

**Comment by markusrubey** [comment]
I couldn't find anything besides http://stackoverflow.com/questions/1194821/heroku-eating-my-custom-http-headers.

**Comment by markusrubey** [comment]
Good news! With Retrofit i get all response headers i need, but only if the request is fired outside the 5 second window. Within the 5 sec window i only get the "Server: Cowboy" head.

**Comment by markusrubey** [comment]
Sorry for the back and forth! It seems like everything works just fine with Retrofit. I'm just left with this 5 sec time window.

**Comment by haslinger** [comment]
1) No need to be sorry, thanks for your patience.
2) The missing headers are in contrary to the docs.
3) Even better: There is an issue with a fix for that. (monkeypatching, bit who cares...)
I 'll come back here, when I implemented and tested it...

**Comment by haslinger** [comment]
Implemented the patch, pushed to Heroku/staging, tested on staging, seems to be fine.
Please try once more...

**Comment by markusrubey** [comment]
Awesome! This fixed it. Getting all headers as expected now.
