### ISSUE TITLE
Landing Page: Emphasize primary call to action

### ISSUE THREAD

**Issue by groe** [where2help/where2help#273]
W2H is a platform for NGOs and volunteers, however the majority of its users, say 90%, are volunteers. I think the landing page should reflect that and emphasize the **primary** call to action, which is "Sign up as volunteer". Right now, the sign up buttons for NGOs and volunteers both have the same size and color, which visually suggests that they are equally important for the current visitor.

I will make a wireframe or draft of what I'm thinking about, so in the mean time these are just some notes for me:
* Embed volunteer sign up form for first-time visitors
* Embed log in form for previously logged-in volunteers (even NGOs?), like XING
* Links or `btn-default` buttons to all NGO related functionality

Further inputs are always welcome!

**Comment by groe** [comment]
[Wirefame](https://github.com/where2help/where2help/files/1026605/W2H-Landing-Page-Wireframe-V2.pdf)

**Comment by groe** [comment]
Wording for the landing page header text:

> [where2help logo]
> Plattform für Freiwillige und Organisationen in der Flüchtlingshilfe Wien

Wording for the feature area:

> ## Wähle aus Hilfseinsätzen von über 50 NGOs
> … wie ABZ Austria, Big Brothers Big Sisters, Caritas, Concordia, Habibi Flüchtlingsprojekte, Integrationshaus, Interface, ProVita, SOS Kinderdorf, The Connection oder Zeitraum.
 
> ## Einmalig mithelfen
> … in Sprachcafés der Agenda 21+, beim Dolmetschen fürs Rote Kreuz oder in der Flüchtlingsbetreuung bei der WWO.
 
> ## Regelmäßig Zeit spenden
> ... unter anderem als Buddy bei der Volkshilfe, im Alltag bei Don Bosco oder beim Unterrichten im WUK.

**Comment by groe** [comment]
@schlingel can you use the wordings above?

**Comment by schlingel** [comment]
OK.

**Comment by schlingel** [comment]
@groe 
Will you provide the logo/pictures which are implied by the circles, should I use fillers or should I omit the whole column?

**Comment by groe** [comment]
@schlingel Let's use the [W2H logo](https://www.where2help.wien/assets/logo_small-0217da54169f3532581f78f7a9d66a6601b32da8ec08aff7a9975fe7942d6a56.svg) as a placeholder for now. We'll have to look for good icons then.

**Comment by groe** [comment]
As of today the new landing page is live at www.where2help.wien!
