### ISSUE TITLE
SEO Heroku / External duplicate content issue

### ISSUE THREAD

**Issue by groe** [where2help/where2help#274]
I just noticed that [Google has indexed the W2H staging environment](https://www.google.at/search?q=site:where2help.herokuapp.com).

Google could consider this [External Duplicate Content](https://support.google.com/webmasters/answer/66359?hl=de).

Maybe a quick fix could be to have a separate [robots.txt](https://github.com/where2help/where2help/blob/master/public/robots.txt) for heroku? Maybe overwrite is as part of the deployment process, @klappradla ?

**Comment by klappradla** [comment]
Sorry for the super late response @groe 😞 
I think it should be pretty straight forward to have a separate `robots.txt` for staging and production. To shortcut it, you could simply use `erb` in it and have it's output depend on the currently set `ENV` - staging vs. production.

**Comment by groe** [comment]
Thanks @klappradla - no worries about the delay

Oh you're right, I didn't even think of that. That's pretty straight forward then, cool!
