### ISSUE TITLE
Test sometimes fails: "Ngos::RegistrationsController PUT update with current password provided updates profile and contact of the NGO"

### ISSUE THREAD

**Issue by groe** [where2help/where2help#289]
Sometimes this test is green, sometimes it's red: https://travis-ci.org/where2help/where2help/builds/278522585

**Comment by groe** [comment]
@schlingel Could you look into that?

**Comment by schlingel** [comment]
@groe 
Yes, just stumbled upon the notification. Will look into it in the next days.
