### ISSUE TITLE
bot notification (connect) not working

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#292]
Tried to enable the fb-notifications as follows:
1. created new user
2. contacted the bot via fb directly (send him a message)
3. followed the link from the bot an enabled the messenger notification in the settings 
4. "send to messenger" (messenger symbol turns to check-symbol and pop-up disapears)
5. so far I´m getting no notifications (changed events...)
6. when I ask the bot via messenger for help (hilfe), I´m getting the initial information to sign up / login

**Comment by groe** [comment]
@votexx According to the database your account has no connected FB account. Can you look at http://where2help.herokuapp.com/users/notifications/edit?locale=en and confirm whether the setting "Benachrichtigungen per Facebook Messenger" is checked?

After step (4) did you click the "Save settings" button as well? Otherwise the change is not saved...

**Comment by votexx** [comment]
Yes, the box for fb-notifications was checked. I now unchecked and re-checked the box, got the pop-up again and said "send to messenger. The Button switches (see picture) and the pop-up disappears. Then I saved the settings, but no notifications so far.

![w2h_sendtomess](https://user-images.githubusercontent.com/19605344/34289388-9a15e552-e6f2-11e7-8d23-9f6f47c68dd9.png)

**Comment by groe** [comment]
You're signed in with your FSW email address, right?

According to the database you have enabled the notifications but your account is not correctly connected to FB. I have just disabled the notifications for you. Can you try re-enabling and re-connecting the account? (Check the checkbox, click "send to messenger", save the settings)

**Comment by votexx** [comment]
Yes, it´s the fsw account. 
When I logged in, the fb-notification was unchecked - so I did the procedure again (this time I´m sure having saved the settings). Changed an event (111) as NGO and still got nothing (except the email-notification I´m not signed up for [#291]). I´ll try to delete the account and initiate the fb-connection again - or do you have any other ideas?!

**Comment by groe** [comment]
We retried and it worked now. Could have been related to the heroku auto deploy from December, who knows.
