### ISSUE TITLE
Homepage and CSS changes

### ISSUE THREAD

**Issue by votexx** [where2help/where2help#313]
To better match the corporate design and comply with WAI standards we would like to have some changes regarding font-color and on the home page.

Change requests are:
- replace the actual color (turquoise) with red (RGB 195/45/60) for Buttons, Hyperlink-Text (quick & dirty drafts attached)

<img width="890" alt="w2h_Anmelden_rot" src="https://user-images.githubusercontent.com/19605344/77076155-b4d44100-69f3-11ea-9e3b-f4fd0d8fe247.PNG">
<img width="945" alt="w2h_Start1_rot" src="https://user-images.githubusercontent.com/19605344/77076160-b6056e00-69f3-11ea-8fde-da1fa6fb8f92.png">
<img width="911" alt="w2h_Start2_rot" src="https://user-images.githubusercontent.com/19605344/77076169-b7cf3180-69f3-11ea-9936-c9f4c33a88e0.png">

- Homepage - change of elements used:

1. w2h brand logo (no changes, except for the logo)
2. three small logos with "descritpion" (no changes, except for the logo)
3. insert an empty "home-section-bg-image" with a heigth of 100px (its a spaceholder)
4. the following "help now" form should be "home-section-bg-light", accordingly with black font-color, button- and hyperlink-color like CSS (red)
5. insert an empty "home-section-bg-image" with a heigth of 100px (same as above)
6. information for NGOs (no changes)

I will submit changed logos asap.

Thank you & kind regards,
Dominik

**Comment by votexx** [comment]
Issue on hold - waiting for approval

**Comment by votexx** [comment]
New logos attached: [w2h_brand_red.zip](https://github.com/where2help/where2help/files/4358455/w2h_brand_red.zip)

changes are approved - please implement

**Comment by mraaroncruz** [comment]
@votexx the new text color is very hard to read
<img width="904" alt="where2help___Freiwillig_für_Wien" src="https://user-images.githubusercontent.com/175984/77340539-be301700-6d2d-11ea-9fad-22f385b553e8.png">

**Comment by mraaroncruz** [comment]
<img width="1026" alt="where2help___Freiwillig_für_Wien" src="https://user-images.githubusercontent.com/175984/77340625-db64e580-6d2d-11ea-9488-f02a4eb12e19.png">

**Comment by votexx** [comment]
@mraaroncruz that´s why we want the "section breaks" (point 3. and 5. in my list) - see also draft attached: 

<img width="706" alt="w2h_homescreen_layout" src="https://user-images.githubusercontent.com/19605344/77401732-be6ff700-6dad-11ea-969d-45db6d4f579f.png">
