### ISSUE TITLE
Translate into English

### ISSUE THREAD

**Issue by ramonh** [where2help/where2help#32]
The basis is there with i18n to get started with it

**Comment by waldgruber** [comment]
note the translation guide lines in the wiki
https://github.com/where2help/where2help/wiki/Translation-Guidelines

**Comment by vierlex** [comment]
doing some cleanup / readying up templates here https://github.com/where2help/where2help/compare/where2help:master...vierlex:loc-de?expand=1
before continuing to translate into english

feedback is welcome, though, there isnt much there yet..

**Comment by haslinger** [comment]
@vierlex you are now added to the team here on Github. Are you part of the slack channel already?

**Comment by vierlex** [comment]
@haslinger nope, not at slack, -> alexander-sulz@gmx.at

**Comment by ramonh** [comment]
I'll plug up the missing ones!

**Comment by klappradla** [comment]
Missing translations will go into new issues based on feedback from FSW.
