### ISSUE TITLE
Do not require authentication for viewing needs#list and needs#show

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#38]
As discussed in #25 we should not require authentication for viewing needs. If clicking on a button to participate in a need, not signed in users should be forwarded to the sign in page and afterwards friendly forwarded back to the participation (as stated in #18 ).

This also requires changes to the navigation.

**Comment by klappradla** [comment]
As it is closely related to navigation and friendly forwarding, I can take care of that.

**Comment by haslinger** [comment]
Regarding the API, it's done now (but only there).
