### ISSUE TITLE
Remove positive confirmation message after successful login

### ISSUE THREAD

**Issue by loncie** [where2help/where2help#40]
The green confirmation message is not necessary (content itself is already a confirmation) and just requires an additional click for closing. I suggest to remove it.
![confirmationmessage](https://cloud.githubusercontent.com/assets/15609804/10907468/9af5bff8-822a-11e5-95e8-67ce04e240f0.png)

**Comment by ramonh** [comment]
I can look into this!

**Comment by klappradla** [comment]
Depends on new navigation, requires no click, etc. Closing this for now.
