### ISSUE TITLE
Web Interface | Calendar: Change Date and Time formats to European Standards

### ISSUE THREAD

**Issue by loncie** [where2help/where2help#41]
Currently US date an time formats are used. Please change to European Format:
Time: 00:00 - 23:00
Date: dd/mm

![image](https://cloud.githubusercontent.com/assets/15609804/10907560/726d483e-822b-11e5-9002-56fea4287196.png)

**Comment by haslinger** [comment]
This and all the other I18n stuff (month names ...) is now changed to Austrian (de-at) via e075df9.
