### ISSUE TITLE
Volunteers can sign up twice for need

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#45]

**Comment by haslinger** [comment]
@markusrubey You can't register twice now. The second time, you get 422 Unprocessable Entity.
But it seems to me, that the error message "Sie sind bereits als Helfer eingetragen!" is not sent back.
Can you confirm that?

**Comment by markusrubey** [comment]
Seems just fine on my end!

{"errors":[{"title":"Sie sind bereits als Helfer eingetragen.","detail":"user-id - Sie sind bereits als Helfer eingetragen.","id":...

**Comment by haslinger** [comment]
Cool, I think I will dump wget. 
I don't get the duplicate record easily using standard Rails validation. I would have to roll my own validation here. 
Whenever we will have an incident where we need it, I will implement it. But I close the issue for now.

**Comment by markusrubey** [comment]
Following quite rare incidents are possible:

volunteering on web app - android data out of date - user volunteering again on android -> duplicate

volunteering on web app - user not logged in on android (so he does not see that he already is volunteering) - user volunteering on android again - prompt login - volunteering request retry -> duplicated

The same goes for canceling/delete volunteering. No changes needed regarding the error response itself, but I am missing a new token?

**Comment by haslinger** [comment]
As long as we talking about the same user account, duplicate entries can't happen. The application logic prevents that in the model, no matter, if you have one android client, one web client or even more of either of these. The code for this looks like this:

``` ruby
   validates :user_id, uniqueness: {
     scope: :need_id,
     message: "Sie sind bereits als Helfer eingetragen."
   }
```
The rails app checks before the actual database statement is executed.

If you are deleting an already deleted record (again, no matter if from web or api), you will get an error message, because that route doesn't exist any more at that moment.

I'm not sure, if I get your question regarding the tokens. Let's see: If the route doesn't exist any more, you should be able to use the last token again.

**Comment by markusrubey** [comment]
Oh! So the token remains valid, should have tried first. Thanks for clarifying.
