### ISSUE TITLE
Wording Registration

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#47]
Hey @loncie & @jakobmaul,

I updated the registration forms for NGOs and volunteers according to https://github.com/where2help/creative/issues/2#issuecomment-154345445. Can you please have a look at the wording. I am missing the "why" text for NGOs [here in german](https://github.com/where2help/where2help/blob/master/config/locales/where2help/views/de.yml#L22) and [here in english](https://github.com/where2help/where2help/blob/master/config/locales/where2help/views/en.yml#L22).

Can you please either change it and open a PR or just write it here and I'll update it afterwards.

**Comment by loncie** [comment]
@klappradla I edited the file and added the following texts:
DE: Schicke deine aktuellen Hilfeanfragen direkt via App an freiwillige Helfer und behalte jederzeit den Überblick wie viele bereits zugesagt haben.
EN: Let volunteers know when and where you need them and view in realtime how many have already signed up.
