### ISSUE TITLE
Expiry, a date?

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#48]
The "Expiry" header for validating tokens is a date or a time span?

**Comment by haslinger** [comment]
It's the unix timestamp (seconds since Jan 01 1970) for the expiration event. Currently it's set to "sign in" + 14 days.

**Comment by markusrubey** [comment]
Just to make sure I'll check again. Got some pretty old dates the last time.

**Comment by markusrubey** [comment]
Update: Seconds is the keyword. For some reason I expected milliseconds. Thanks you!
