### ISSUE TITLE
Allow users to pick which abilities they have

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#5]

**Comment by klappradla** [comment]
If we add #13 we can skip this for the MVP, I think. Picking categories would be most useful if users get pinged if their category is requested near them etc. This mechanism is too sophisticated for the MVP, I'd say. Let's wait for usage feedback first.

**Comment by pferdefleisch** [comment]
:+1:

**Comment by haslinger** [comment]
+1 - after MVP.

**Comment by haslinger** [comment]
Changed ticket subject: Categories on user level are now called abilities.

**Comment by haslinger** [comment]
Admin part is now done, self service is missing.

**Comment by haslinger** [comment]
Nope, there is also still a bug in admin, data is not persisted. I have to dig into this.

**Comment by klappradla** [comment]
Missing strong params :v: 
https://github.com/where2help/where2help/blob/master/app/admin/user.rb#L17

**Comment by haslinger** [comment]
@klappradla Yes, with a weird syntax for has_many_through:  https://github.com/where2help/where2help/blob/master/app/admin/user.rb#L22 
and some more stuff was missing: https://github.com/where2help/where2help/commit/31361adf8f33edcf70319005209acf5b3af4da70

In addition formtastic now works everywhere and has correct bootstrap styling.

**Comment by haslinger** [comment]
The formtastic class was unneccessary and is removed meanwhile.
