### ISSUE TITLE
Inform volunteers when need was deleted

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#54]

**Comment by markusrubey** [comment]
Is this related to emails I guess?

**Comment by klappradla** [comment]
Yes. Email is kinda "cross-platform", so I'd go for that first.

**Comment by Althaire** [comment]
Hi, do you already have a mailer set up for any other features on the app or does this needs to be set up?

**Comment by klappradla** [comment]
Mailers are already set up: the [volunteers_mailer](https://github.com/where2help/where2help/blob/master/app/mailers/volunteer_mailer.rb) is for instance informing volunteers when a need is updated, using [this](https://github.com/where2help/where2help/blob/master/app/jobs/notify_job.rb) job.

**Comment by klappradla** [comment]
Will be part of the whole notification process anyway... so closing this.
