### ISSUE TITLE
Error when editing need from the calendar

### ISSUE THREAD

**Issue by ramonh** [where2help/where2help#56]
When we hit submit after editing a need from the calendar, I get the following:
`No route matches [PATCH] "/needs/51"`

**Comment by ramonh** [comment]
I believe this is from a broken route in the form

**Comment by klappradla** [comment]
Happy to look into this :panda_face:

**Comment by ramonh** [comment]
Fixed in c29f82e1a60febb1a3156c9b206f24877ad08158
