### ISSUE TITLE
Allow users to edit their profile and cancel their account

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#58]
Allow users to edit their profile (including email and password) and cancel their account. Devise already handles all this for us. So we only have to to two things:
- [x] Link the respective views and adapt them to match the rest of the app
- [ ] Add the missing fields to the views and the parameters to Devise' strong parameters

**Comment by hassanshaikley** [comment]
Is this webapp actually being used? If anyone wants to chat about it I may be willing to contribute.

**Comment by klappradla** [comment]
Hey @hassanshaikley thanks a load for your offer and your interest in the project! Really appreciate this!
The webapp is part of a bigger ecosystem of other (mobile) apps and services and is supposed to help organising volunteers helping refugees. For the time being we're just wrapping things up for beta testing our ideas with our local Viennese partners to see a) if it is useful and b) how we need to proceed.

The webapp also serves as an example project for a local ruby learning group, therefore these smaller issues are more or less occupied as exercises for them. Therefore, I'm really sorry having to disappoint you here, I think we currently don't have the time, resources and overview for further contributions and evolving of the webapp until we received feedback from the rolling out beta phase.

I hope you understand, and again, thanks for your offer!

**Comment by hassanshaikley** [comment]
= ) 

Thanks for the response!

Take care.

**Comment by haslinger** [comment]
Users con now change their accounts.
