### ISSUE TITLE
Introduce NGO models

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#70]
Introduce own NGO model with:
- [x] own registration / sign_up workflow with Devise  
  - see [here](https://github.com/plataformatec/devise#configuring-multiple-models) for how to set up devise with multiple models
- [x] need two types of confirmation:  
  - email confirmation (Devise)
  - admin confirmation (admins by hand)

## NGO
```ruby
## Attributes (besides what Devise already requires: password, tokens, etc.) ##
name: string*
email: string*
phone: string*
company_register: string* # please improve naming here, FSW wants "Firmenbuchnummer / UID / ZVR"
admin_confirmed_at: datetime # prefer date to boolean here, because more expressiveness

## Associations
has_many: events
has_one: contact
```

## Contact

FSW also requires an NGO to have a personal contact (including address) attached to it. I would separate this out into a own model with own validations:

```ruby
## Attributes ##
first_name: string*
last_name: string*
street: string* # street could include door number I'd say
zip: string*
city: string*

## Associations ##
belongs_to :ngo
```

**Comment by klappradla** [comment]
According to FSW, NGOs may be allowed to cancel their account. If they do, all their published *(and current)* events should stay active. There are different ways to handle this, one easy solution would be to just **"freeze"** an NGOs account. So it is only marked as destroyed, not really destroyed from the db.
There are various ways to implement this (state machines, deleted flag, etc).

Other possibility: destroy account and use Null Object pattern for all remaining events without an NGO.

Happy on more ideas on this here.

**Comment by klappradla** [comment]
![untitled diagram](https://cloud.githubusercontent.com/assets/3491815/13091192/43192f40-d4fa-11e5-8fd7-75c3fc1b27e5.png)

**Comment by haslinger** [comment]
+1 on freezing. 
If data privacy is an issue here, update the attributes of the freezed records to self explanatory values. But this keeps the ideas of the user records alive and distinguishable.

**Comment by klappradla** [comment]
Current state on the **freezing** topic: NGOs can cancel their account via `DELETE destroy`. This will reset `confirmed_at` and `confirmation_token`, but keep their `admin_confirmed_at`.

They get a flash message telling them their account was **"deactivated"**.

Not sure if it's the best solution, but I'd say it's working one for now. Account can still be fully deleted by admins anyways.
