### ISSUE TITLE
Enhance User model

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#71]
Enhance User model:
- [x] get rid of no longer needed attributes
- [x] introduce new attributes requested from FSW
- [x] user's email address needs to be confirmed (Devise)

## Attributes
**basic:**
```ruby
first_name: string*
last_name: string*
email: string*
locale: string # necessary to send emails in the right language
admin: boolean
````

**advanced**
In addition to that, FSW also wants users to specify:
- languages
- abilities (e.g. doctor, lawyer)

*No fixed idea on how to to this yet.*

**Comment by haslinger** [comment]
I vote for proper models for languages and abilities and has_many relations.

**Comment by klappradla** [comment]
@haslinger I second you on this. Admins can then create / edit these languages and abilities the way they like without us having to interfere. I'll update the data model.

**Comment by haslinger** [comment]
* 'Doing' is misleading, maybe 'Handle', 'Can', 'Master' or 'Able'
* 'Volunteer' could be 'Work', 'Do' or 'Help'

**Comment by ramonh** [comment]
This should now be set up fully as of e3ca239

**Comment by ramonh** [comment]
As discussed, we've renamed the association tables to be called `languages_users` and `abilities_users`.

**Comment by haslinger** [comment]
So I guess, as we have abilities meanwhile, we are only missing languages. Will do this next.

**Comment by haslinger** [comment]
Push notifications should be disable-able (according to FSW). As we skipped then alltogether (as far as I remember), this is not an issue anymore.
Languages can now be changed by users and admins.
So I think, we can close this.
