### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#72]
User with admin status have access to the application's admin interface. They should be able to:
- [ ] confirm / edit  NGOs
- [ ] edit events, users

Plug in a rails engine for this: Thoughtbot's [Administrate](https://github.com/thoughtbot/administrate)

*Alternative: [ActiveAdmin](https://github.com/activeadmin/activeadmin)*

**Comment by haslinger** [comment]
Tried the adminstrate demo, it's not responsive.

The other old, big one I know is [Rails Admin](https://github.com/sferik/rails_admin)
I mostly only use [Datatables](https://www.datatables.net/) and standard scaffolding besides that. 
For huge admin infaces I use [w2ui](http://w2ui.com/web/), but this is over the top here.

**Comment by klappradla** [comment]
I'd say it's not super necessary for the admin interface to be responsive. It's not a part of the app for lots of users, these user are not supposed to go there every minute and they probably shouldn't misuse their superpowers over huge tables of sensitive production data when bored on the train.

Anyways, I think one could expect responsiveness for Administrate in the near future. There are already PRs and issues pointing in that direction.

I'm super familiar with ActiveAdmin (also not responsive). But I guess it's more effort to set up and harder to get in for people not familiar with it.

**Comment by haslinger** [comment]
I still have the feeling, Administrate is super clunky. E.g. click on edit leads you to show, not to edit, where you have to click edit a second time. Destroy in the demo app crashes. It's pre 1.0. I don't feel trust. (I am used to Hobo and there the generated admin interface just works, but that's not the way to go for us ...)

**Comment by klappradla** [comment]
Then let's go with ActiveAdmin. I can take care of that. Bonus here: continuous development, German translated UI, lots of users / lots of resources on how to use it.

**Comment by klappradla** [comment]
*Note to self: pulling in aasm here, because whole process of admin confirming / locking / deactivating ngos goes outta hand*
