### ISSUE TITLE
Event model replacing "Need" model

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#73]
Introduce **Event** to replace Need model.

## Behavior

1. NGOs create Events
2. NGOs publish created Events
2. Events are automatically split up into Shifts
3. Users attend Shifts

## Attributes

```ruby
category: integer* # mapped to enum
description: text
volunteers_needed: integer*
starts_at: datetime*
ends_at: datetime*
shift_length: integer* # defaults to 2 hours, may also be double value?
address: string* # FSW prefers this to "location"
lon: float # pulled from API in background
lat: float # pulled from API in background
aasm_state: string* # could also be boolean, depending on how we implement this
````

## State
NGOs should be able to create Events, but hiding them from Users until **publishing** them. Therefore, an Events needs states:
- pending (default)
- published (visible for users)
- cancelled *optional*

## Shifts
more on that in a separate issue

**Comment by klappradla** [comment]
As specified by FSW: Users do not attend Events directly, they attend **TimeSlots** of an Event. Therefore, there is also no counter_cache for volunteers in the Event model (only in the TimeSlot).

![untitled diagram 1](https://cloud.githubusercontent.com/assets/3491815/13092392/f6feff58-d4ff-11e5-944c-ee0dc7e6d9fd.png)

**Comment by ramonh** [comment]
As discussed on 3.3.16, shifts will not be automatically generate from events after these are created, but rather give NGOs the ability to create shifts for individual events in a form.

**Comment by klappradla** [comment]
**Update**

- [ ] add association between `Event` and `Ngo`
- [ ] associate new event with `current_ngo` when creating
- [ ] remove `shift_length` attribute since we don't use it
- [ ] add title attribute as discussed in #97

**Comment by ramonh** [comment]
All update tasks being done, I think we can close this, right @klappradla?
