### ISSUE TITLE
Shift model

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#74]
Introduce new Shift model:
- Shift are automatically created from Events *(in backgroundjob probably)*
- Event specifies length of Shift from start- to end-time
- Users volunteer for Shifts *(not for the Event directly)*

```ruby
## Attributes
starts_at: datetime*
ends_at: datetime*
volunteers_needed: integer*
volunteers_count: integer # counter_cache column, name after association

## Associations
belongs_to :event
has_many: volunteers # could also name it "volunteerings", "appointments", etc.
```

## Workflow
1. NGO creates Events with start-time, number of shifts, length of shifts (default 2 hours)
2. Create Shifts from Event:
  2. Event's number of `volunteers_needed` is equally split up between it's Shifts, generating the Shift object's `volunteers_needed` value

## Questions
- What happens to Shift if NGO changes Event (starts_at, ends_at, volunteers_needed)
- What happens if an Event is less than 2 hours long?

**Comment by klappradla** [comment]
Possible answer on question 1 (Aaron already wrote this in the notes): NGOs cannot change Events once a single User volunteered for a TimeSlot.

To simplify this, one could forbid any changes to Events once they are **published** and therefore only create TimeSlots when an Event changes its state to **published**.

**Comment by haslinger** [comment]
I bet, that the fixed 2 hours will change. It's such an arbitrary number and I have seen a different practise at Hauptbahnhof (8h shifts). A would just see it as a default in suggested times. 
Btw. Shift would be shorter to type than TimeSlot :-)

**Comment by klappradla** [comment]
Going with **Shift** :tada:
I'll update the issue's description for more flexibility than 2 hours.

**Comment by klappradla** [comment]
Updated diagram:
![untitled diagram 2](https://cloud.githubusercontent.com/assets/3491815/13144070/8812caf8-d648-11e5-825a-abd758a71569.png)

**Comment by klappradla** [comment]
For the record: this is how the data model looks

```ruby
t.integer  "event_id"
t.datetime "starts_at"
t.datetime "ends_at"
t.integer  "volunteers_needed"
t.integer  "volunteers_count",  default: 0
t.datetime "created_at",                    null: false
t.datetime "updated_at",                    null: false
```
