### ISSUE TITLE
NGOs create Events

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#75]
NGOs can create Events (see #73 for model definition) via the Calendar interface.
- [x] Events are initially set to **pending** *(or just the not-published-state)*

## Event form
- use datepicker for start and end-time

**Comment by haslinger** [comment]
I am opposing modals as the logic gets more complex on the frontend and I saw users failing getting them. So +1 on seperate page.

**Comment by haslinger** [comment]
There were also missing links to publish, edit and delete in the list view. These are done now as well.
