### ISSUE TITLE
Change calendar interaction

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#76]
Change calendar interaction to suit new way of inputing Events #75 
- [ ] Remove drag-click interaction
- [ ] Single click to create new Event (see #75), trigger only **new** action
- [ ] Do not allow picking dates in past
- [ ] Remove "Agenda" view
- [ ] Translate calendar entries (e.g. category)
- [ ] Use color to show event state -> published means no changes allowed

**Comment by klappradla** [comment]
I'd also fully remove the dragging interaction for calendar entries for the sake of simplicity. If not, it needs to be fixed to:
- not jump back
- update event accordingly
- only be allowed for events where changing is still allowed

**Comment by haslinger** [comment]
The calendar should further more be integrated with the rails assets pipeline.

**Comment by haslinger** [comment]
The bug is in the Email configuration, changing a calendar entry dumps on the server with 
```
Sent mail to admin@example.com, android_user@example.com, normaluser@example.com, *censored by @haslinger because several actual email adresses from FSW in here*, new_user@example.com (75.7ms)
2016-02-17T08:46:08.221494+00:00 app[web.1]: Actor crashed!
2016-02-17T08:46:08.221496+00:00 app[web.1]: Net::SMTPFatalError: 550 Unauthenticated senders not allowed
```

Furthermore the current mailing settings tries to send emails to several accounts at FSW and at the cinema you gave a presentation at! That's why i censored the list above.

**Comment by klappradla** [comment]
Good to know!
Mailings are definitely something to go over again. Including Suckerpunch - it was updated to v2 and works way better now, especially when included as ActiveJob backend (using this setup currently at work).

**Comment by haslinger** [comment]
Decision: We move from a calendar view to a list view.
