### ISSUE TITLE
NGO Event list

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#77]
NGO needs to have a list view for their events: table of events
- [x] orderable for all columns
- [x] filterable for category, all/upcoming/past
- [x] change prompt for delete to "Soll der Eintrag wirklich gelöscht werden?"
- [x] notify registered users when a shift they're volunteering for is deleted
- [x] distinguish between past and upcoming Events

Some event can still be edited by the NGO (see #75 for policy).
- [x] after editing an event, navigation should go back to list view
- [x] find an appropriate format for displaying timeslots

**Comment by haslinger** [comment]
ordering, filtering and searchung could be achieved by Datatables locally, furthermore columns are automatically hidden on low-width displays. https://github.com/rweng/jquery-datatables-rails

**Comment by haslinger** [comment]
Translated it.
