### ISSUE TITLE
User Schedule

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#79]
Users should have a list view for their shifts.
- [ ] filterable for category, all/upcoming/past
- [ ] default ordering: chronologically, upcoming first
- [x] FSW: "bug: hopping out of need puts need in list as *past* (no matter if actually upcoming)"  
 **(should completely remove event from this view)**

**Comment by haslinger** [comment]
Has anybody confirmed this bug? I can't.

**Comment by klappradla** [comment]
It was on the FSW list - did not try it myself.

**Comment by klappradla** [comment]
**Update**

This view should be reachable for users under **`/schedule`**. The route can be defined as a singular resource, since we will be pulling out only the current_user's schedule anyways. Controller just needs a index action for now.
