### ISSUE TITLE
UI on needs list looks like I am already signed up for need

### ISSUE THREAD

**Issue by pferdefleisch** [where2help/where2help#8]
I think "Helfen", green, with a check looks like I am already helping. Maybe "Ich will Helfen" without a checkbox, maybe a different color. I think of green in this context normally as a state of already committed. At the very least, I think the check should go away. But I also think the "x" may be ok to stay on "Absagen"

What do you think?

**Comment by phillipp** [comment]
I agree that it is not very clear how the state toggle works there. Maybe a button is not the best UI element for state... a giant check box might be a UI element that's more common and easier recognized?


Von: Aaron Cruz
Gesendet: Montag, 19. Oktober 2015 09:30
An: refugeeHackVienna/iamin
Antwort an: refugeeHackVienna/iamin
Betreff: [iamin] UI on needs list looks like I am already signed up for need (#8)



I think "Helfen", green, with a check looks like I am already helping. Maybe "Ich will Helfen" without a checkbox, maybe a different color. I think of green in this context normally as a state of already committed. At the very least, I think the check should go away. But I also think the "x" may be ok to stay on "Absagen"

What do you think?

**Comment by klappradla** [comment]
I totally agree. The green button is semantically wrong. The original design suggest a *I'm in* button. We could go with a neutral (means some non-lightsign color) one, toggle it to a green checked one when signed up and maybe show a red x one when hover afterwards (won't be seen on mobile though). When the user hops out, we can again switch back to the neutral one.

![buttons](https://cloud.githubusercontent.com/assets/3491815/10588830/761fcf94-76a8-11e5-9de4-593b1529aec4.png)

**Comment by pferdefleisch** [comment]
I don't think we ever need a green check. Neutral or X or even "Ich will helfen" or "Absagen", which is the most understandable.
If we want colors, maybe a low alpha green or red.

Tagging as bug
