### ISSUE TITLE
Event show view for Users (volunteers)

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#81]
The Event view for Users (volunteers) should show:
- [x] map for location
- [x] name of NGO *(avatar / gravatar nice to have)*
- [x] address, description, time, number of people
- [x] `I'm in` buttons for available Shifts

![mockup](https://cloud.githubusercontent.com/assets/3491815/13129095/deb8a0a8-d5da-11e5-83c4-72346e648286.png)

**Comment by haslinger** [comment]
I am missing the kind of work that has to be done. Do I fit?

**Comment by markusrubey** [comment]
As @klappradla mentioned it would be nice to have a strong visual difference between **I'm In** = **true** and **I'm In** = **false** for the event details page. So I came up with the following:

![event_detail_flow](https://cloud.githubusercontent.com/assets/2398384/13877145/41f3bb86-ed09-11e5-8cba-b0c22a39674b.jpg)

1. If **I'm In** = **false** we could just show a button for helping/volunteering

2. If that button is pressed we list the time slots 

3. If  one or more **I'm In** = **true** show a "thank-you" - massage above the time slots.

_(Note: The views from **1** and **3** are only replacing the "shifts" - view from **2**)_

**Comment by klappradla** [comment]
I agree there should be an obvious visual difference telling people wether they already opted into a shift or not (btw: **opt in** - trying to establish this expression now). But I think we have a different idea of a) the process of a user opting in and b) the display of information during this process.

Here's how I currently implemented it:
![shift_opt_in](https://cloud.githubusercontent.com/assets/3491815/13879153/20ba59cc-ed16-11e5-8a55-6c931719be8a.png)


**Why so?**
I display a list of available **Shifts**, ordered by their `starts_at` time and in future then also filterable. Clicking on one items displays all information about the shift's **Event** (where to go, description, etc) and a button to opt into **this certain Shift**.
The way you display it, clicking on a **Shift** brings the user to a view of the **Event** again listing all available Shifts - as in the mockup from the bible. I thought this is obsolete, as it just requires the user *again* to search through the list for her desired time, replicating what has already been done at the **Shift**'s list view.

I think you can come up good reasons for both approaches. My motivation was:

> What's the most obvious, idiot- and fail-resistant for non-power-users to get it?

That's why I chose this approach. But it's of course free to change / adapt.

**Comment by markusrubey** [comment]
Oh, I see. Just to make sure I interpret this correctly: 

The view in **1** and **4** is **Events** (previously Home) on the web app?

_Is it possible to fill the database with some dummy events and set up some @example.com accounts like we had in the previous version so I could check things out? (Maybe extract this into another issue)_

Your implementation would keep the Detail Screen uncluttered where my concept would keep the list on the Events Screen clean. Also the Detail Screen would basically stay the same as in the previous version using your approach. My only concern now is FSW. Is your implementation "confirmed"?

**Comment by klappradla** [comment]
Yes, **1** and **4** is **Events** / **Home**.

And yes, please open up an issue for sample data!

My implementation is not *confirmed*, it relies on artistic freedom and the discussions we had about it in various hacking sessions. Your solution keeps the event list short, but it can be filtered to be short anyways, so there's not a huge necessity to do it.

**Comment by markusrubey** [comment]
I agree. Alright, going with it... and wont change it :smile:

**Comment by klappradla** [comment]
Refactoring is life 🚜 ✌️
