### ISSUE TITLE
Event list on homepage

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#82]
The homepages shows an event list.
- [x] only show **published** events
- [x] only show events with available shifts

### List item
- [x] shows time, location
- [x] is clickable / has button to shift show view

**Comment by haslinger** [comment]
For me, that's a list, not a feed. A feed is fixed content or a data stream to be interpreted by a different application, e.g. rss feed. There is also no need in starting to stream here.

**Comment by klappradla** [comment]
Old draft with online-shop-like filters on the left sidebar
![523b640c-878e-11e5-9369-c9039a29d9f2](https://cloud.githubusercontent.com/assets/3491815/13161415/d1c6331a-d69d-11e5-9cd3-d30f5ca06b53.png)

**Comment by klappradla** [comment]
Some inspirations on list layout *(should still be pure bootstrap afterwards, nothing fancy)*:

![untitled-2](https://cloud.githubusercontent.com/assets/3491815/13161642/5476d71e-d69f-11e5-911a-b42cc72c64e4.png)

![screen_shot_2011-11-15_at_09 37 38](https://cloud.githubusercontent.com/assets/3491815/13161644/591f454e-d69f-11e5-8e36-91a5e38d88c2.png)

![contact_list2_1x](https://cloud.githubusercontent.com/assets/3491815/13161646/614a775c-d69f-11e5-911a-f2f8024c586a.jpg)

![favorites_1x](https://cloud.githubusercontent.com/assets/3491815/13161797/60e0bb86-d6a0-11e5-859d-b4048f436df6.png)

**Comment by markusrubey** [comment]
Oh nice, just discovered this issue. 

I thought about round images (instead of the pin thing) as well, and I'm all for it. I would love to stay on the material design specs to keep things clean and familiar (and easy to implement ;). So I'm thinking about dropping those unnecessary calendar- & location- icons as well and move more towards something like your first pic: 

![image](https://cloud.githubusercontent.com/assets/2398384/13215076/38d9e2a6-d953-11e5-8d3c-4302ee20019f.png)

List-Group: I think having the whole item as a touch target would make great improvements towards accessibility

**Comment by klappradla** [comment]
Yes @markusrubey I remembered you talking about having the material design specs as an orientation, so I read through some of the guides on it. My thoughts on the list view are directly derived from it. Totally with you on having the whole element touchable / klickable and getting rid of visual clutter.

**Comment by markusrubey** [comment]
Having the Time-Slot feature in place, how would a secondary action work out? 

Maybe we should instead of an actual action just show the volunteering state as an icon beside the volunteers-needed count, like:
<img src="https://docs.google.com/drawings/d/1olh32LuNP2plc8zM4LsHvNbl3p_dc1WvpqCOWglC1Zc/pub?w=473&amp;h=235">

**Comment by klappradla** [comment]
The secondary *action* would - same as e.g. in the "Favourites" example above - indeed only indicate state, not work as a point of actual *interaction*. There's a single click / touch interaction on the whole element / whole row.

Two state indicators could convey possible interaction, you're right (again, same as in the "Favourites" example above). Problem with the number: hard to say what it stands for without the icon next to it being expressive enough or having a column heading.

The most minimalistic layout would be:
![1](https://cloud.githubusercontent.com/assets/3491815/13235948/79a58ac4-d9c1-11e5-8995-18ecd7a648aa.png)
*has all necessary information, secondary action say if going / not going*
 
More information:
![2](https://cloud.githubusercontent.com/assets/3491815/13235986/c3f90bbe-d9c1-11e5-8a90-75ac51ec9c76.png)
*prominent category could be important, maybe more important than organization*

Table like layout could use column-header for more expressiveness:
![3](https://cloud.githubusercontent.com/assets/3491815/13236007/e5d5d7c6-d9c1-11e5-8b5e-4fdd4ac97648.png)
*number would be understandable*

**Question:**
How important is which of information?
- `Category` is encoded twice (icon and title)
- `Organization` might be a key factor why people join
- `Time` is information wise most important
- `VolunteersNeeded` might not bee too important after all....

What do you think?

A minimalistic version could also look like this then:
![4](https://cloud.githubusercontent.com/assets/3491815/13236172/0be80104-d9c3-11e5-94dc-1caa7c3b2d13.png)

**Comment by markusrubey** [comment]
I would agree that `Time` is the most important info, followed by `Category` and `Location`. I see some value in `Organization` but not to a degree that I want it in the mobile view. 

Also good point on having `Category` already in the image. Meaning the most minimalistic version looks very tempting to me, but I can't tell if the category name could be dropped or not. Wouldn't miss `VolunteersNeeded` though.

**Comment by markusrubey** [comment]
But i really like the icon with the number in the "favorites" example. Maybe we could do the same if we switch from the bookmark icon to something that suits the `VolunteersNeeded`count. A match like "I heart" to heart-count is missing.

**Comment by klappradla** [comment]
Totally agree.
If you search for icons around `refugee, volunteer, help`, etc. you find things like **[ic_face](https://design.google.com/icons/#ic_face)** and various combinations of **hearts** and **hands**. So maybe simplified outlined / filled versions of the original *where2help*-icon could be interesting for this job:
![icon](https://cloud.githubusercontent.com/assets/3491815/13269544/97e07ec8-da88-11e5-85a2-33640f3ba8fe.png)

Could be too complex for a simple indicator though. I'd like something very simple where we can easily toggle the fill. If you look at for instance **[ic_people](https://design.google.com/icons/#ic_people)**, I could also imagine a outlined / filled version of this speaking the meaning we want.

I also thought various ways of calendar icons like you find them in [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/). But `Heart`, `Person` and `Hand` seem to suit the context better.

**Comment by markusrubey** [comment]
Great idea with the hand in combination with the logo! Having both hands or the whole icon would be too complex, yep. Had a look at the font but couldn't quite find the right hand guesture. I'm not that happy with the hands in the logo either ;) Will keep my eyes open.

Not so fond of the heart for the same reasons as with the bookmark icon. Just doesn't work well with the countdown.

**Comment by klappradla** [comment]
There's for instance the **[Charity Icon](https://thenounproject.com/term/charity/4060/)** (it's open source afaik), the **[Volunteer Icon](https://thenounproject.com/term/charity/259876/)** (also as **[outlined version](https://thenounproject.com/term/charity/260176/)**), the **[Donate Icon](https://thenounproject.com/term/charity/29964/)** and, one of my all time favs: the **[Do Charity Icon](https://thenounproject.com/term/charity/324691/)** ✌️

**Comment by markusrubey** [comment]
:joy: at your all time favorite pick. Awesome site! The **[Charity Icon](https://thenounproject.com/term/charity/4060/)** would make a pretty neat replacement for our current logo. As for the indicator the **[Volunteer Icon](https://thenounproject.com/term/charity/259876/)** could fit, or maybe extract a single hand from the logo? Or a single hand from **[../term/hand](https://thenounproject.com/term/hand/)**. I like where this is heading!

**Comment by klappradla** [comment]
Again totally agree. Since the **Charity Icon** is under CC licence, we could also modify it to our needs. Here's for instance a round one I found on Dribble:

![heart_1x](https://cloud.githubusercontent.com/assets/3491815/13298838/ba60c380-db38-11e5-8c7e-cfc3fe4ad1a4.jpg)

For the count, @haslinger had some nice input: it would be of great value to have both, the number of people needed + the number of people already volunteering. It would make some items more demanding than others for instance.

![1](https://cloud.githubusercontent.com/assets/3491815/13299201/69b007a0-db3a-11e5-9c2d-9633efb726ca.png)

**Comment by markusrubey** [comment]
Hmm, mind changed. Seeing the more rounded version from dribble and having both counts as suggested by @haslinger, why not just go with the "handed" - heart then. Expressing our "brand" throughout the app would be a nice design decision too.

**Comment by klappradla** [comment]
👍
Is `users_going / users_needed` the natural way to put it? I wasn't sure...

**Comment by markusrubey** [comment]
Yep. X fromY :thumbsup:

**Comment by klappradla** [comment]
After we dropped categories vor Shifts/Events, the list's primary action icon could display something more meaningful and of more valuable information then just the same basic icon for each entry.

Some ideas:
- could show a **calendar icon** with the date, resembling the calendar icon on IOS
  - [Codepen example](http://codepen.io/anon/pen/gbxXLP) on how to archive this with our font awesome icon font
- could show **tiny map**
- could show iconified **count for volunteers / volunteers_needed**
  - small pie chart / pacman to be filled
  - progress-bar style bar to be filled up
- could show **profile-image** for ngo
  - would have to enable image-upload or gravatar-support for NGOs
  - gravatar has [some pretty decent defaults](https://en.gravatar.com/site/implement/images/), too (if no image for email address available)

**Comment by pferdefleisch** [comment]
I think the first two sound the most useful for the user.

but for the other two:

- Do they care how many volunteers are signed up? Maybe it would encourage them if more people are signed up?
- Does anyone care who the NGO is? Maybe this is a question for FSW.

**Comment by pferdefleisch** [comment]
PS. This issue is getting pretty noisy and could be broken down into smaller chunks (back referencing this issue).

**Comment by klappradla** [comment]
One might care who's the NGO in the sense of *"oh I prefer hanging out with these guys"*, but it's not super important.

I personally also prefer the calendar icon - it would allow to get rid of the date in the **`date - time`** line next to the icon and have the time more prominent.

**Comment by pferdefleisch** [comment]
And the NGO icon can be just a click away on the shift detail page (if there is such a page, I don't remember the decision)

**Comment by markusrubey** [comment]
Would go with **date** for the same reasons as @klappradla mentioned. Or with the volunteer count, which could convey urgency -> resulting in "motivation".

**map**: Would be quite some "work-load" inside a list-view, plus it would be too tiny to get any use out of it.

**profile image**: Would be nice to have one in the profile, but I don't think that pretty pictures would end up in the list -> could end up quite noisy.

**Comment by markusrubey** [comment]
Would go with **date** for the same reasons as @klappradla mentioned. Or with the volunteer count, which could convey urgency -> resulting in "motivation".

**map**: Would be quite some "work-load" inside a list-view, plus it would be too tiny to get any use out of it.

**profile image**: Would be nice to have one in the profile, but I don't think that pretty pictures would end up in the list -> could end up quite noisy.

**Comment by pferdefleisch** [comment]
With the map, you could just use google maps static maps. https://developers.google.com/maps/documentation/static-maps/. But it's probably moot because of your first paragraph.

**Comment by markusrubey** [comment]
Yep. There is also a LiteMode for MapView/MapFragment which is basically the same just without the quota constraints. The point I'm tying to make is that the map would not be bigger then a profile picture here on github (at least on mobile), which would not justify all the network requests needed, because it's too small to get any use out of it.
