### ISSUE TITLE
Flash message missing after successful email confirmation

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#85]
After clicking the confirmation message in the email sent, you are presented with the login screen.I think the flash message indicating the successfull confirmation is missing. 
I believe @ramonh, you have been working on this?

**Comment by klappradla** [comment]
Flash messages are not part of the layout yet. Wanted to do that in one shot when adding navigation and container layout.
You can just throw them in now, if you depend on them.

**Comment by ramonh** [comment]
Pretty much what @klappradla said :sweat_smile:
