### ISSUE TITLE
Single sign in form for users and ngos

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#86]
Use a single sign-in form for both Devise models, for instance:
- [ ] add own SessionsController, point both model's `new` and `create` paths there
- [ ] overwrite the [default Devise `new` and `create` actions](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb)
- [ ] logout can stay separate for both models

**Comment by klappradla** [comment]
Problem to solve here: how to map a UI users understand to two different **`SessionControllers`**. Guessing the user's class might be tricky since email addresses are not uniq over both models.

Solutions I can think of:
* use single (new) controller and have uniq email addresses across both models
* adjust navigation (#83) to have two different login buttons (NGO and Volunteer)
  * could be dropdown on current login button
  * would be 2 different (existing) controllers, no problems with duplicate emails
* display two forms (with two different action-paths) on the signin page

**Comment by haslinger** [comment]
* One more way: [Log in as NGO] - Button on login-form for users

**Comment by klappradla** [comment]
Thanks @haslinger! Indeed a usual approach too, something like *"Are you an NGO?"* or *"Login as NGO instead"* - have seen this somewhere at least, so users should get it.
