### ISSUE TITLE
Landingpage and registration

### ISSUE THREAD

**Issue by klappradla** [where2help/where2help#87]
- [x] Add landingpage with links to navigation for both types of users
- [x] Add terms-and-conditions stuff to registration forms

**Comment by klappradla** [comment]
For NGO registration: group fields logically belonging together (e.g. city, zip) into the same line to make the form not as huge as it currently is.

**Comment by markusrubey** [comment]
Is it necessary to validate the terms-agreement e.g. with a checkbox or is it fine to just refer to it like most apps do?

**Comment by klappradla** [comment]
From what I remember reading in the FSW bible, they need the checkbox. I haven't implemented this in the app yet though.

**Comment by markusrubey** [comment]
Checked the bible and found nothing. So I guess they where happy with the checkbox validation.

From playing around with a bunch of apps I also noticed that most require 6 characters for the password - we currently require 8, maybe that's too harsh?

**Comment by klappradla** [comment]
Yes, sorry, "checkbox-validation" is what I meant, and is also how I'll do in in the webapp.

With the password-lenght you are prop. right - hate it myself too - I'll open up an issue to lower this to 6.
