### ISSUE TITLE
Wording/Phrasing of UI Components 

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#91]
Opening this issue for brainstorming on wording, phrasing and translations of any kind.

- **My Shifts**: Would translate to "Schicht"  -  "Meine Schichten" which feels a little bit odd cause it's very "work-related". This could be more positively described with something like **My Schedule** (Mein Zeitplan) or **My Events** (Meine Termine)

- **Home**: Works perfectly on the web, but with a tabbed mobile app "Home" seems wrong since "Home" is the page with the tabs inside (If that makes any sense). Maybe **Events** (Termine) or something more inviting like **Explore** (Erkunden) could do

**Comment by klappradla** [comment]
Totally agree with *My Shifts* sounding too work-/mining-related. **My Events** / **Meine Termine** and **My Schedule** / **Mein Zeitplan** work equally well. Bonus of *schedule* might be that one would not be tricked into questioning weather as a user one could create events too, then beeing "my events".

So I'd go with **My Schedule** and the translation (nice translation btw.).

Doing to, we can also switch **Home** to **Events** on both web and mobile to a) stay consistent and b) not interfere with the next menu items.

**Comment by markusrubey** [comment]
Good point! I haven't even thought of the NGO view. So I'd go with **My Schedule**  for normal users as well and leave **My Events** to the NGO page.

**Comment by haslinger** [comment]
We use "Event" and "Schicht" for now.
