### ISSUE TITLE
Tab Bar Icons (mobile)

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#92]
I am thinking about picking the following icons:

- Icon [**Events**](https://design.google.com/icons/#ic_event)

- Icon [**My Schedule**](https://design.google.com/icons/#ic_schedule)

- Icon [**Profile**](https://design.google.com/icons/#ic_face):

**Comment by klappradla** [comment]
Looks good!
I'm not sure yet if / where to add icons in the webinterface. But for mobile (tabs I guess) these look nifty!

**Comment by pferdefleisch** [comment]
@markusrubey I have it set up like this in iOS as well. Do you think "My" is necessary?

**Comment by markusrubey** [comment]
Sorry for closing too early. Nice! Nope it's not, let's get rid of it.

**Comment by pferdefleisch** [comment]
NP. Danke!
