### ISSUE TITLE
Self registration

### ISSUE THREAD

**Issue by haslinger** [where2help/where2help#94]
As @markusrubey pointed aut, there are two bugs in the self registration: The link in the Email points to the wrong domain and there is a bug in the view, that should be rendered afterwards.

**Comment by haslinger** [comment]
I fixed the registration link domain in production settings via 9f6a310 .

**Comment by haslinger** [comment]
Heroku migrations where lagging far behind, that fixed the view problem. @ramonh , please push to heroku and run migrations when you create a new one.

**Comment by haslinger** [comment]
@markusrubey you should now be able to use the confirmation link in the confirmation email.

**Comment by ramonh** [comment]
Will do, thanks for the heads up @haslinger!
