### ISSUE TITLE
Event Title (Location)

### ISSUE THREAD

**Issue by markusrubey** [where2help/where2help#97]
Previously we had categories as title of an event, now it's the event location. The problem I am running into is that there is only one field in the model called "address". Typically an address includes street name, number, district, ... which would result in a pretty long and confusing title. 

_(Guessing game continues)_ To add to that the bible states the following:

>  Zusatzfeld „Adress-Zusatz“ ist hilfreich (gerade an Orten wie Westbahnhof – z.B. „bei
> Ausgang Äußere Mariahilfer Straße“).

Maybe we need to expand our model to cover the following:

- **location** (Something like "Westbahnhof" becomes the title)
- **address** (Street, Street-Number, or empty)
- **address-desc** (Further address descriptions, or empty)

**Comment by klappradla** [comment]
I see your problem.
An alternative solution would be to introduce a **`title`** field for events, e.g. *"Essensausgabe am HBF"*, *"Bus vom Land"*.. could limit it to around 100 chars.

For the location as title:
If what we call **location*** is part of the address, you could also just strip away some parts of the longer address string. But there might be situations where what we refer to as ***place** or **location** is not really part of the address, e.g. "Bahnhofsvorplatz", "Parkplatz", etc. So we could introduce **`place`** or **`location`** as an additional field, but I wouldn't go as far as expanding it to 3 fields.

I left the Church long ago, being realistic, what the bible states as *"Adress-Zusatz"* should just be part of the description. Anything else makes the form explode and NGOs will have a harder time figuring out which information goes in which field.

Both, **`title`** and **`location`** can make sense. I tend to think, **`title`** would be more meaningful.

**Comment by markusrubey** [comment]
A dedicated `title` sounds even better for what I'm trying to accomplish.

**Comment by markusrubey** [comment]
Ooops :v:

**Comment by klappradla** [comment]
Discussion time is over, nailing this in #73

**Comment by klappradla** [comment]
@markusrubey I added the title and updated the data on staging.
